### ISSUE TITLE
Version 1.0.1 fails on openSuse 15.1 (new kernel)

### ISSUE THREAD

**Issue by euneuber** [tuxedocomputers/tuxedo-control-center#10]
Hi,
great job this control center! Beautiful design!

It worked until yesterdays kernel update. Kenel info is now:

> Linux linux-xx000.suse 4.12.14-lp151.28.48-default #1 SMP Fri Apr 17 05:38:36 UTC 2020 (18849d1) x86_64 x86_64 x86_64 GNU/Linux

**Comment by vinzv** [comment]
Thanks for the kind words!

Did the dkms successfully build during the update progress? Did you eventually reboot after the kernel update being finished?

**Comment by euneuber** [comment]
Hi,
how do I check for those dkms build results/artifacts?
Yes, I did reboot multiple times..

**Comment by tuxedoxt** [comment]
You can check with `dkms status` that the module is installed for the current kernel.

**Comment by euneuber** [comment]
@tuxedoxt thank you!
@vinzv you are right, the dkms where not for this "new" kernel. I had to remove and auto install them. Maybe openSuse does not trigger the rebuild if the kernel version changes only in build number?

Consider this resolved for me. Thnak's again!
