### ISSUE TITLE
[Feature Request] make it easier to switch between profiles

### ISSUE THREAD

**Issue by yeus** [tuxedocomputers/tuxedo-control-center#100]
My use-case:

I can run my Pulse15 with a USB-C power bank. This means, that even though the Pulse15 is running on battery it will switch to a high-performance profile. --> I would like to be able to:

- switch profiles using manually defined shortcuts (could be done by giving tuxedo-control-center a commandline interface, 
   this would also make it easy to automate profiles...)
- switch profiles using right mouse click in the system tray.

Thx for the great contributions to the OS community!

**Comment by tuxedoxt** [comment]
Interesting ^^

Can confirm that at least temporary tray switching will come in a not too distant future. Will make a note of CLI interest.

**Comment by othbert** [comment]
Few things to add with the profiles which I felt would fit here and not worth cluttering your issues with new requests:

- I'd love to be able to cycle a set of (or all) profiles with successive Fn + F6 presses (or whatever the default keybind would be / OS level shortcut key).
- Also, the ability to either remove the default profiles or change their configuration, so we can use those nice graphics ourselves to depict which is the eco profile and which the full power etc.
- If webcam control isn't possible (as on pulse14) no need to take up space showing those icons on the profile selector page, then 2 rows (with their save buttons) might fit on the screen by default.

Also, would like to echo the sentiment in the OP, thanks for the great software (and hardware!)

**Comment by brunoais** [comment]
@othbert 
See if this works for you:
https://github.com/brunoais/tuxedo-control-center-profile-changer
You can setup keyboard shortcuts to call my C program to change to a certain profile.
See the README.md about its usage. If you need help or have an issue, just file an issue there.

Maybe that can work for you until tcc team accommodates this.

**Comment by tuxedoxt** [comment]
Meanwhile.. the temporary profile switch through the tray menu is now available since v1.1

(For third party tools it means it can be done through the dbus interface as well)

**Comment by acheronfail** [comment]
I'm looking through the DBus APIs (using `d-feet`) and I can only see methods relating to _getting_ profiles. I can't see any DBus methods that relate to _setting_ the current profile.

How can I **set the profile** using DBus? (are there any docs for this?)

**Comment by crissi-tuxedo** [comment]
Hey Archeronfail, 

I described how to switch profiles over the commandline in more detail in issue  #318 

best regards, Crissi
