### ISSUE TITLE
Allow customizing startTCCAccelerator

### ISSUE THREAD

**Issue by brunoais** [tuxedocomputers/tuxedo-control-center#101]
Currently, startTCCAccelerator is a constant that is hardcoded to `Super+Alt+F6`.
I suggest that being just a default value which can be overridden with command line options or a settings file.

In my case, I'd like to have it as `Super+F9`

**Comment by tuxedoxt** [comment]
Hello,

I snuck this feature test-wise into the latest release, feel free to have a playaround :)

```
--startTCCAccelerator=Accelerator|none
```

where Accelerator => https://www.electronjs.org/docs/api/accelerator

This feature of electron is a little bit... quirky, all combinations do not work, global shortcut registration is probably very dependent on the system it's running on.

**Comment by brunoais** [comment]
OK! Thank you.

**Comment by tuxedoxt** [comment]
Closing this for now.
