### ISSUE TITLE
Error in /var/lib/dpkg/info/tuxedo-control-center.prerm during upgrade of tcc to 1.0.13 (pre installed Ubuntu)

### ISSUE THREAD

**Issue by vonloxley** [tuxedocomputers/tuxedo-control-center#103]
`/var/lib/dpkg/info/tuxedo-control-center.prerm: Zeile 4: [: upgrade: Ganzzahliger Ausdruck erwartet.`

**Comment by sevillaarvin** [comment]
This is a problem with the `.deb` file, per the `prerm` script:

```sh
#!/bin/bash

# On RPM update don't remove anything
if [ "$1" -gt 0 ]; then
    exit 0
fi

# ... SNIP
```

Based on my [quick google](https://medium.com/swlh/introduction-to-debian-maintainer-script-flow-charts-6f76423b80d9), `prerm` script is passed two arguments:

`prerm upgrade 1.2.3`

Therefore, I belive `$1` should be `$2` instead.

P.S. deb files taken from https://deb.tuxedocomputers.com/ubuntu/pool/main/t/tuxedo-control-center/

**Comment by tuxedoxt** [comment]
Erm. yeah this can be ignored if I remember correctly. I believe it was also silenced in recent versions. This should probably be closed.

Ah yeah here it is: 8323d17
