### ISSUE TITLE
Enabling maximum performance profile option for cpu spams journal

### ISSUE THREAD

**Issue by aardbol** [tuxedocomputers/tuxedo-control-center#104]
This is the log that's being spanned all over the journal:
```
Apr 28 08:58:42 moon tccd[13326]: CpuWorker: Unexpected value boost => true instead of false
Apr 28 08:58:42 moon tccd[13326]: CpuWorker: Incorrect settings, reapplying profile
```

Disabling the option and using "boost" level instead solved the issue

**Comment by tuxedoxt** [comment]
Thanks, which device/distro/kernel are you running on? Any custom bios settings?

@Matombo Something known here?

**Comment by Matombo** [comment]
Propably a wrong check (Max performance should ofc use boost, contrary to what the log message says)
Looking into it.

**Comment by Matombo** [comment]
Can't reproduce on my test device.
@aardbol What Laptop and CPU do you have?

**Comment by aardbol** [comment]
model: Aura 15 with Ryzen. Manjaro kernel 5.10.32

**Comment by Matombo** [comment]
Which ryzen exactly?

**Comment by aardbol** [comment]
4500U

**Comment by aardbol** [comment]
Correction: 4700U

**Comment by Matombo** [comment]
Found and fixed, will be in the next release.
Thanks for the report.

**Comment by aardbol** [comment]
Closing because this seems to be solved now.
