### ISSUE TITLE
XP15 gen 12 4k screen brightness doesn't change

### ISSUE THREAD

**Issue by captain-hak** [tuxedocomputers/tuxedo-control-center#113]
Hello, 
I have a Tuxedo Book XP15 with a samsung amoled 4k screen, which is great by the way!
My only concern is that the Fn key + F8 ( to make the brightness lower) does trigger the % bar on ( budgie + ubuntu installed via web fai + kubuntu installed by my own) but the screen brightness isn't actually changing.
Is there any known issue about this?
Is there a way to solve this? 
It could save me some minutes while on battery!
Thank you for your answers!

**Comment by tuxedoxt** [comment]
Hello,

I believe the OLED screens need the package `tuxedo-oled-brt`.

If installed through the webfai it should already be there. If not, it needs to be included.

Please let me know if package install plus reboot solves the issue.

```
sudo apt install tuxedo-oled-brt
reboot
```

**Comment by captain-hak** [comment]
That was what was missing, I installed it and it's working now
