### ISSUE TITLE
tuxedo_io_lib usage (on pulse)

### ISSUE THREAD

**Issue by sleepingtux** [tuxedocomputers/tuxedo-control-center#114]
Hello, 

i am not sure if it's directly related to the lib or the tuxedo-keyboard module but here is the things.

COMPUTER:
TUXEDO PULSE
Bios updated to the latest. 

I use the tuxedo_io_lib on a C++ project. 
To sumarize here is the context
TuxedoIOAPI io;
io.SetEnableModeSet(1);
io.GetFanTemperature(nbFan, m_temp);
while(run)
{
  if (m_speed <> previousSpeed)
        io.SetFanSpeedPercent(nbFan, m_speed);
  sleep(1);
}

In fact, if i set fanspeed every loop, all is ok.
But if i test the speed in order not to apply the same value again and again, the default curve goes back and the fan speed up to 30% like default. 

You could easly test it by just test:
TuxedoIOAPI io;
io.SetEnableModeSet(1);
io.SetFanSpeedPercent(0, 20);
while(1)
   sleep(2)

you will see that even if the cpu stay cold on idle (less then 50° for me), after a time it goes back to 30% that is the default curve.

it's like something rollback the fanspeed on the EC. 
i think it's EC/Bios related that reset the setting from time, but that should not be normal no? 

Is there any risk to setfanspeed all the second? Is there any risk to hurt the EC by writting fan speed all the time inside? 
Why does EC took back the fan control after a time even if we set manual mode?  

Thank's

**Comment by sleepingtux** [comment]
Hello, i could confirm the problem on the pulse.

Here is an easy test:
    auto start = std::chrono::system_clock::now();
    m_run=true;
    TuxedoIOAPI io;
    io.SetEnableModeSet(1);
io.SetFanSpeedPercent(0,20);
    int speed = 0;
    auto end = std::chrono::system_clock::now();
    while (m_run) {
        sleep(200);
        io.GetFanSpeedPercent(0,speed);
        if (speed != 20)
        {
          end = std::chrono::system_clock::now();
          cout << "Speed: "<<speed << endl;
          m_run=false;
        }


    }
    std::chrono::duration<double> elapsed = end - start;
    std::cout << "Elapsed time: " << elapsed.count() << "s"<<endl;
    io.SetFansAuto();
    return 0;

If i let it turn (with no big temperature, i always take a look about that! don t worry), after a moment, fan goes back to 30% (cpu temp was less then 50°).
here is the console result:
./TEST_FAN 
Speed: 30
Elapsed time: 3600.85s

So after 3600s, it roll back to automatic speed. But even if i apply speed every 200s, it will roll back to automatic after a time. And when i set a speed it stop to be automatic but it's like there is a timer that roll back to automatic every 1h.

**Comment by sleepingtux** [comment]
I confirm the problem on the pulse.
Every 1h the fan goes to 30%.

**Comment by sleepingtux** [comment]
Hello.

Could we have some information about that? 
Why does the ec roll back to automatic mode every one hour? (even if you apply settings)

Is there any problem to apply fan speed every second? (it will not wear out the EC by writte inside every second?)

**Comment by tuxedoxt** [comment]
Hello,

sorry for the delay. These are the type of questions that we not always have a clear answer to.

However, the way we manage to set fan control for these devices comes with an automatic timeout once every hour. We've had this question as well and got the deliberate timeout confirmed. So far this is the best general implementation we have.

As for how often to write/check fan control we currently do it similarly, approx every second. There should not be any problem writing this often.

**Comment by sleepingtux** [comment]
Thank you for your answer. 
it's a shame that it roll back to automatic every hour. :/ 

Write every second to set exactly the same speed temp is good is a waste of battery/power :/ 
Even if it's not "big" it's the case. :/
