### ISSUE TITLE
BUG: Polaris 17. Changing profile turns brightness to maximum

### ISSUE THREAD

**Issue by brunoais** [tuxedocomputers/tuxedo-control-center#116]
Since 1.0.14, in my Polaris 17, every time I change the profile in use which is supposed not to change the brightness, makes the brightness go to maximum.

For example, for the 3 default profiles:
Default -> 100% brightness
Cool and breezy -> 100% brightness
Powersave Extreme -> 60% brightness

How to fix this?

**Comment by brunoais** [comment]
Meanwhile, the problem seems solved.

**Comment by Uhter** [comment]
Hi @brunoais,
I've actually the same issue on Polaris 17. The problem has been solved after a TCC update?

**Comment by Uhter** [comment]
Thanks for your answer.

It doesn't seem to be a TCC issue but a kernel one. Someone had the [same problem](https://mastodon.xyz/@Nils/109709313532916914) on a MacBook Pro with Fedora.
We both **downgraded from kernel** 6.1.* to 6.0.* and it **fixed the brightness issue**.
