### ISSUE TITLE
BM1707 BIOS & EC Versions

### ISSUE THREAD

**Issue by antis81** [tuxedocomputers/tuxedo-control-center#120]
Recently experienced similar symptoms as described in issue #117.

Unfortunately the downloadable BIOS & EC versions do not match and I'm a bit confused on what is right here:

File | BIOS (Website) | BIOS (zip) | EC (Website) | EC (zip)
----|----|----|----|----
Combined | 1.07.11 | 1.07.09 | 1.07.13 | 1.07.11
EC Only | \-\- | \-\- | 1.07.13 | 1.07.12
BIOS Only | 1.07.11 | 1.07.11 | \-\- | \-\-

Could you write a short feedback and update the website please about which are the correct versions to install?

**Comment by tuxedoxt** [comment]
Hello,

thanks for the notice. I'll make sure it gets sorted out.

I believe for your device we recently got a working fix, I'll let you know when it's available for download.

**Comment by StevenSeifried** [comment]
Hello @antis81
we corrected the downloads. The new EC version 1.07.15TR1 fixes the issue

**Comment by antis81** [comment]
@tuxedoxt Sorry to bother once more. The combined package still contains the old EC & BIOS versions.

**Comment by StevenSeifried** [comment]
Please don't use the combine packages. Only use the separate BIOS & EC packages
