### ISSUE TITLE
CPU and GPU fan profiles should be separate 

### ISSUE THREAD

**Issue by brunoais** [tuxedocomputers/tuxedo-control-center#13]
The CPU and GPU have different temperature performances.
In my PC's case:

The CPU runs:
Max Turbo until 70ºC
Turbo until 80ºC (In "performance" fans should be max around here)
Max acceptable temp 100ºC (fans must be 100% here to prevent raising to 105ºC)
Max temp 105ºC

The GPU runs:
Max turbo 84ºC (In "performance" fans should be max by here)
Max acceptable temp 89ºC (fans must be 100% here to prevent raising to 91ºC)
Max temp 91ºC

In all configurations, the GPU won't get the fan at 100% before forcing a system crash to protect itself.

**Comment by frosstatx** [comment]
its true, or more simply  add a profile fan type "game mode" with 100% fan with  GPU in 84C

**Comment by tuxedoxt** [comment]
As of v1.0.3 GPU's have their own respective fantables. Existing fan tables have also been revised and two new added.
