### ISSUE TITLE
Add fan always on option

### ISSUE THREAD

**Issue by samodadela** [tuxedocomputers/tuxedo-control-center#141]
Can you please add a **fan always on option** to TCC. It is currently possible to choose fan curves: Silent, Quiet, Balanced, Cool, Freezy. My Tuxedo Aura 15 is making a noise when the fan spins up from 0% to 20% - it's annoying. The only fan profile that keeps the fan on iz Freezy - however the minimum speed is around 30-35% and it's also very noisy even with minimal load.

The request is for an option that would prevent TCC for stopping the fan - regardless of the CPU temperature. This way I could choose Balanced, check "fan always on" - this way I could use Balanced without having to listen to that pesky noise.

Starting/stopping the fan also shortens the fans life.

**Comment by tuxedoxt** [comment]
Ah that explains it, thea feature in included as of TCC v1.1.0.

Update available?

**Comment by samodadela** [comment]
Not yet... hope it'll be in with the next manjaro update.

**Comment by samodadela** [comment]
tcc just got updated on Manjaro to 1.1.0... minimum fan speed works:
![image](https://user-images.githubusercontent.com/16334222/142902220-bcef57d3-90d8-4a8c-b3fc-a3dd5453ffb7.png)

Thanks!

**Comment by tuxedoxt** [comment]
Great! Closing this  :)
