### ISSUE TITLE
CPU Temp and CPU Fan is not supported on your model

### ISSUE THREAD

**Issue by LLCJ4** [tuxedocomputers/tuxedo-control-center#142]
Hi,
I'm running a clevo N141zu with elementary OS 6, and fan control seems to be not supported (as well as cpu temp).
I did not knew this issue on Ubuntu 20.04 LTS with the same machine.

Also, when i tried to install TCC with the terminal as indicate [in this page ](https://www.tuxedocomputers.com/en/Infos/Help-and-Support/Instructions/Add-TUXEDO-Computers-software-package-sources.tuxedo#), the key did not work.
So i install the software with[ this depots ](https://deb.tuxedocomputers.com/ubuntu/pool/main/t/) which seems to be updated (last one from 2021-08-27).
So for now, i have the software running but without possibilities to change anything in the profile.

Did i miss something ?
Thx

**Comment by LLCJ4** [comment]
Any advice to make it run on my pc ?

**Comment by crisidev** [comment]
I have the same problem and for me it is related to the kernel version. Ubuntu recently shipped 5.13, which causes the issue you described. I have reverted back to 5.11 and everything works in the control center.

Tuxedo folks, is there a plan to support newer kernels than 5.11?

**Comment by LLCJ4** [comment]
I'm still on 5.11 (Elementary OS 6), and it's not working :/ 
![Capture d’écran de 2021-11-10 22-37-27@2x](https://user-images.githubusercontent.com/92229898/141197935-7e233042-7ccb-4230-bb30-9e624c89622b.png)

**Comment by crisidev** [comment]
> I have the same problem and for me it is related to the kernel version. Ubuntu recently shipped 5.13, which causes the issue you described. I have reverted back to 5.11 and everything works in the control center.
> 
> Tuxedo folks, is there a plan to support newer kernels than 5.11?

Scratch what I said. I think I was just missing some kernel module on the new kernel that was not built properly by dkms.

I triggered a full dkms rebuild and reinstall, for all the kernels I have on the machine, reboot and now 5.13 works perfectly:

```sh
ls /var/lib/initramfs-tools | \
    sudo xargs -n1 /usr/lib/dkms/dkms_autoinstaller start
```

**Comment by augustoicaro** [comment]
Hey @LLCJ4, I was with the same problem here with my eluktronics MAG-15 running elementary os 6. The @crisidev tip of reinstalling modules on the kernel solved the problem. So my steps to fix it was:

1. Find the kernel version that you are using: `ls /var/lib/initramfs-tools`, mine is **5.11.0-41-generic**
2. Then install linux headers for this kernel: `sudo apt install linux-headers-5.11.0-41-generic`
3. Reinstall modules on kernel: `ls /var/lib/initramfs-tools | sudo xargs -n1 /usr/lib/dkms/dkms_autoinstaller start`

**Comment by augustoicaro** [comment]
@LLCJ4 you're welcome. Another tip is to install [STE](https://github.com/salihmarangoz/system_tray_extensions) to control the keyboard light and light bar. I see that you already enabled the system tray indicators (There is a known bug in this indicator system, but let's check some things).

First, can you try to see in Tuxedo Control Center system tray if you can see the profiles in the profile menu? It should show your profiles like this:

![image](https://user-images.githubusercontent.com/4841488/145244076-0112073e-7b01-45fc-a698-349f3ee88e18.png)

**Comment by LLCJ4** [comment]
Hi @augustoicaro,

Yes i have this tcc system tray enabled, but seems i have exactly the same problem that you described in #162 ...

So for now i have just created a custom profile and stay on, without open the system tray (or just pass over with my cursor ...) In this way, seems to keep the profile i want, but i'm kind of stuck with it (and it's ok i guess !)

**Comment by Duke194** [comment]
I'm on Ubuntu 20.04 with Kernel `5.13.0-10035-tuxedo`. A few days ago I needed to repair my ubuntu because after an update it won't boot properly. So I used `boot-repair` to fix that issue and since that time I got no Fan and CPU Temp readings. Can anyone explain how to restore that functionality? I tried the dkms rebuild and reinstall, but nothing changed.

**Comment by tuxedoxt** [comment]
> I'm on Ubuntu 20.04 with Kernel `5.13.0-10035-tuxedo`. A few days ago I needed to repair my ubuntu because after an update it won't boot properly. So I used `boot-repair` to fix that issue and since that time I got no Fan and CPU Temp readings. Can anyone explain how to restore that functionality? I tried the dkms rebuild and reinstall, but nothing changed.

Sounds like driver didn't build for the booted kernel. If you have `tuxedo-keyboard` installed

```
sudo dpkg-reconfigure tuxedo-keyboard
```

could suffice, otherwise install `tuxedo-keyboard`

```
sudo apt install tuxedo-keyboard
```

**Comment by Duke194** [comment]
> > I'm on Ubuntu 20.04 with Kernel `5.13.0-10035-tuxedo`. A few days ago I needed to repair my ubuntu because after an update it won't boot properly. So I used `boot-repair` to fix that issue and since that time I got no Fan and CPU Temp readings. Can anyone explain how to restore that functionality? I tried the dkms rebuild and reinstall, but nothing changed.
> 
> Sounds like driver didn't build for the booted kernel. If you have `tuxedo-keyboard` installed
> 
> ```
> sudo dpkg-reconfigure tuxedo-keyboard
> ```
> 
> could suffice, otherwise install `tuxedo-keyboard`
> 
> ```
> sudo apt install tuxedo-keyboard
> ```

Hey man, thanks for the advice. I was finally able to try it out and your reconfigure hint was indeed the solution.

**Comment by pietrangelo** [comment]
I'm on Suse Linux Tumbleweed and after the 6.5.8-1 Kernel installation Tuxedo was unable to recognize both the CPU and the Fan. I fixed it running:

```bash
sudo dkms autoinstall
```

**Comment by jansilvo** [comment]
I have a similar problem on my Lenovo Thinkpad X13 Gen3 (Intel) with Tuxedo OS. 
Tuxedo Control Center displays the message "_The feature is not supported on your model_" only for CPU Fan.

Kernel: 
6.5.0-10008-tuxedo #8 SMP PREEMPT_DYNAMIC Mon Nov  6 14:48:30 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

I've tried the different solutions proposed in this thread, but none seem to work. Can someone help me please?

**Comment by vinzv** [comment]
> Lenovo Thinkpad X13 Gen3 (Intel)

That's the reason. TCC only works full-featured on TUXEDO models.

**Comment by jansilvo** [comment]
> That's the reason. TCC only works full-featured on TUXEDO models.

Simpler than I expected. Thank you @vinzv !
