### ISSUE TITLE
Where is the tray icon file?

### ISSUE THREAD

**Issue by amithiel** [tuxedocomputers/tuxedo-control-center#146]
Hi!
I'm trying to create a monochromatic icon for tuxedo control center icon.
Do you guys know where is it stored on a debian based distro?
cheers

**Comment by sevillaarvin** [comment]
Not sure for debian but for manjaro it's stored at:

```
/usr/share/icons/hicolor/64x64/apps/tuxedo-control-center.png
/usr/share/icons/hicolor/24x24/apps/tuxedo-control-center.png
/usr/share/icons/hicolor/128x128/apps/tuxedo-control-center.png
/usr/share/icons/hicolor/256x256/apps/tuxedo-control-center.png
/usr/share/icons/hicolor/32x32/apps/tuxedo-control-center.png
/usr/share/icons/hicolor/48x48/apps/tuxedo-control-center.png
/usr/share/icons/hicolor/96x96/apps/tuxedo-control-center.png
/usr/share/icons/hicolor/16x16/apps/tuxedo-control-center.png
```

try:

```sh
sudo find /usr -name "tuxedo-control-center*.png"
```

**Comment by vinzv** [comment]
Not sure where AUR (and Manjaro) packages put files. But in *buntu/Debian it's located at `/opt/tuxedo-control-center/resources/dist/tuxedo-control-center/data/dist-data/`.

Have fun!

**Comment by leuchtrakete666** [comment]
thanks for the hint. i changed the icons in this directory as well. the tray icon is still in full color.
