### ISSUE TITLE
Request to build packages for Fedora

### ISSUE THREAD

**Issue by rexmtorres** [tuxedocomputers/tuxedo-control-center#149]
I am running Fedora and I really wanted to install TUXEDO CC.  I've tried installing the openSUSE packages but I get the error:
`- nothing provides libappindicator3-1 needed by tuxedo-control-center-1.1.0-1.x86_64`

I tried installing `libappindicator` but it doesn't match the version needed by CC.

It would be very much appreciated if you can support Fedora.

**Comment by CatRequies** [comment]
There is an unofficial package in Fedora's Copr repository for TCC and `tuxedo-keyboard` that uses `libappindicator` 's Fedora version. Works fine for me with 35.

**Comment by rexmtorres** [comment]
> tuxedo-keyboard

Thank you so much for pointing me to this!  I just installed it and it seems to be working fine.  Hopefully, the team will officially support Fedora.

**Comment by tuxedoxt** [comment]
Although I believe official support for fedora is unlikely. If the current RPM works for fedora and just changing the `libappindicator3-1` dependency is enough? A dependency fix should not be a big deal. Can someone confirm that `libappindicator3-1` -> `libappindicator` is sufficient?

Assuming this is the case I'm thinking an alternative dependency should solve it.

**Comment by KallePM** [comment]
I can confirm that changing the dependency is enough.
That's pretty much all I did for my copr build.

**Comment by tuxedoxt** [comment]
Here's a test build of the current release but with alternative dependencies

https://cloud.tuxedo.de/index.php/s/bKMsZcef2SgSbZT
pw: rpm-deps

If it works and doesn't break install on suse distros I'll include it as a combined RPM package.

**Comment by KallePM** [comment]
Cannot test for suse but I just installed it on fedora and it works as expected.

**Comment by hannes-hochreiner** [comment]
I support the request and can confirm that changing the dependency works.

I exchanged the package ``libappindicator3-1`` for the package ``libappindicator-gtk3`` the key ``config/rpm/depends`` in the function ``buildSuseRpm`` in the file ``build-src/electron-builder.ts``.

**Comment by tuxedoxt** [comment]
Since `v1.1.3` there are alternative dependencies for the rpm package. Should solve the fedora issue.
