### ISSUE TITLE
Can't open app : FATAL:gpu_data_manager_impl_private.cc(439)] GPU process isn't usable. Goodbye.

### ISSUE THREAD

**Issue by dafffooo** [tuxedocomputers/tuxedo-control-center#150]
Hi,
I can't really say with which kernel or nvidia drivers this started, but when I try to open tuxedo-control-center app, it crashes with:

`~> tuxedo-control-center
/bin/sh: line 1: prime-select: command not found
/bin/sh: line 1: prime-supported: command not found
[25908:1109/014133.367623:FATAL:gpu_data_manager_impl_private.cc(439)] GPU process isn't usable. Goodbye.
Trace/breakpoint trap (core dumped)
`

System:
`openSUSE Tumbleweed 20211030
~> uname -r
5.14.14-1-default
~> rpm -qa | grep nvidia
libnvidia-egl-wayland1-1.1.7-3.1.x86_64
nvidia-gfxG05-kmp-default-470.74_k5.14.2_1-44.1.x86_64
nvidia-glG05-470.74-44.1.x86_64
x11-video-nvidiaG05-470.74-44.1.x86_64
kernel-firmware-nvidia-20211027-1.1.noarch
nvidia-computeG05-470.74-44.1.x86_64
`

All the best,
Davor

**Comment by sevillaarvin** [comment]
Do you have prime installed?

https://en.opensuse.org/SDB:NVIDIA_SUSE_Prime

**Comment by LinAGKar** [comment]
`prime-select: command not found` is probably because prime is not installed, but `GPU process isn't usable` is due to seccomp violations with electron on glibc 2.34 (https://bugs.launchpad.net/ubuntu/+source/glibc/+bug/1944468). This has been fixed in Electron 14, and the fix has been backported to Electron 12 and 13, so TCC needs to get updated to the latest Electron.

**Comment by dafffooo** [comment]
Hi, I do have suse-prime installed, however my account didn't have path to prime-select script. 

```
# rpm -q tuxedo-control-center suse-prime
tuxedo-control-center-1.1.0-1.x86_64
suse-prime-0.8.4-1.1.noarch

# which prime-select
/sbin/prime-select
```

So after this...

```
% export PATH=$PATH:/usr/sbin
% tuxedo-control-center 
/bin/sh: line 1: prime-supported: command not found
[17563:1120/001207.273939:FATAL:gpu_data_manager_impl_private.cc(439)] GPU process isn't usable. Goodbye.
Trace/breakpoint trap (core dumped)
```

But this works, thx for the bug link =>
`tuxedo-control-center  --no-sandbox`

--
Davor
