### ISSUE TITLE
Settings reset to current values after I change in UI

### ISSUE THREAD

**Issue by Invertisment** [tuxedocomputers/tuxedo-control-center#151]
I'm trying to change my performance profile and every time I click "save" it resets to what it had before.
Other checkboxes in Settings also work the same way.
Is there some kind of log somewhere? Maybe I didn't install it right or some kind of permissions are missing?

Model:
Stellaris 15

**Comment by sevillaarvin** [comment]
Try opening `dmesg --follow` in the terminal before clicking "Save". Then after clicking "Save" see if there are any output/errors. Try also with `journalctl -b -x --follow`.

**Comment by Invertisment** [comment]
No errors in any of them.

I couldn't run `dmesg --follow` without root so I ran with `sudo`.
Also I tried `journalctl` with and without sudo. No logs appeared.

**Comment by tuxedoxt** [comment]
Hello,

do you get a password prompt as a popup window after clicking save?

If not, there might be a problem with pkexec on your system. For example try

```
pkexec whoami
```

in a terminal. There should be a popup for password input.

**Comment by Invertisment** [comment]
```
pkexec whoami
==== AUTHENTICATING FOR org.freedesktop.policykit.exec ====
Authentication is needed to run `/usr/bin/whoami' as the super user
Authenticating as: _ (_)
Password: 
```

**Comment by sevillaarvin** [comment]
Try pressing `Ctrl + Shift + I` when focused on the TUXEDO Control Center app, then click the `Console` tab, are there any errors when you perform the action?

![image](https://user-images.githubusercontent.com/33614172/142211284-72910e77-08df-48f3-852a-d7b13c5820b8.png)

**Comment by Invertisment** [comment]
> Try pressing `Ctrl + Shift + I` when focused on the TUXEDO Control Center app, then click the `Console` tab, are there any errors when you perform the action?
> 
> ![image](https://user-images.githubusercontent.com/33614172/142211284-72910e77-08df-48f3-852a-d7b13c5820b8.png)

empty

**Comment by Invertisment** [comment]
Funny thing is that I can change my profile from the appbar menu.

**Comment by Invertisment** [comment]
I resolved the issue on my local machine. I think that installing `mate-polkit` did the trick because as the environment had `pkexec` as a binary it still needed:
https://wiki.archlinux.org/title/Polkit#Authentication_agents

Should I close it or do you want to use this issue and add some kind of notification for the user?

**Comment by tuxedoxt** [comment]
Hello,

good that you managed to track down the problem. I am not familiar with what the package provides, but it could mean it sets some standard policies. In an upcoming version there will be one included polkit policy file for changes to tccd (at least) from the gui.

As far as I have seen the standard policies are always there on the standard distro installs.

> Funny thing is that I can change my profile from the applet menu.

If you mean the tray menu, that talks over a dbus interface that doesn't need privileges.

I'll note it and close the issue.

**Comment by Invertisment** [comment]
It doesn't enforce a policy. Instead it simply provides a GUI helper window that can actually pop up. 
Because when you execute `pkexec` in your app it asks the password in the shell session and doesn't prompt the user.

**Comment by Invertisment** [comment]
Then why the UI doesn't use that dbus interface? Because if the applet can circumvent the `pkexec` then it's privilege escalation.

**Comment by tuxedoxt** [comment]
> Then why the UI doesn't use that dbus interface? Because if the applet can circumvent pkexec then it's privilege escalation.

Well, there are many opinions on what should be allowed with and without. For now it's possible to switch *existing profiles* temporarily without but needed to change settings and state assignments.
