### ISSUE TITLE
Question: Disabling CPU cores: logical/physical

### ISSUE THREAD

**Issue by gary094** [tuxedocomputers/tuxedo-control-center#159]
Hello!

Maybe this is a bit of a silly question but I'd like to know the following:

In the tuxedo control center it is possible to reduce the number of active cores when modifying a profile. I understand it says "_Number of logical cores_" next to the slider. But what happens if I reduce the number of active cores to lets say _3_? Does it disable a logical or a physical core first? 

Or another example: What if I set the number of active cores to 4? Does it turn my CPU to a 2+2 (physical+hyperthreading) or will it be a 4 physical CPU only then?

Thank you!

**Comment by tuxedoxt** [comment]
Hello,

the question is interesting. So far there's no sophisticated method. It's simply set in the order they are enumerated in `/sys/devices/system/cpu/`.

In the case of most Intel CPUs as example, currently looking at an i7-1165G7. This means for logical cores `0-7` they correspond to "physical cores": `0, 1, 2, 3, 0, 1, 2, 3`.

Should be listable with `cat /sys/devices/system/cpu/cpu*/topology/core_id`.

As far as I know the order is not specified though and if so could vary.

sysfs docs: https://www.kernel.org/doc/Documentation/ABI/testing/sysfs-devices-system-cpu

**Comment by gary094** [comment]
Hi,

thank you so much for this link!
I have a InfinityBook S14 Gen6 (which I like very much!) and chose the i5-1135G7. I ran the command you provided and got the same output.

If I understand correctly all physical cores are mapped to logical ones like the following:

|physical core|logical core|
|-----------------|---------------|
|0|0|
|0|1|
|1|2|
|1|3|
|2|4|
|2|5|
|3|6|
|3|7|

Now theoretically if I reduce the _logical core slider_  from 7 (or 8 since the control center seems to start counting from 1) to lets say 3 I would be disabling physical core 3 and 2.

**Comment by tuxedoxt** [comment]
Yes, to my understanding that seems correct.

(TCC setting chooses the number of cores to leave on though so 3 means 0, 1, 2 would remain on and it would be a 3 core without hyperthreading.)

**Comment by gary094** [comment]
Thanks for clarifying!
