### ISSUE TITLE
Add packages for Ubuntu 16.04

### ISSUE THREAD

**Issue by vinzv** [tuxedocomputers/tuxedo-control-center#16]
_Originally requested by @girone in https://github.com/tuxedocomputers/tuxedo-control-center/issues/6#issuecomment-621116279_

Packages for Ubuntu 16.04 are missing in  http://deb.tuxedocomputers.com/ubuntu/dists/

**Comment by tuxedoxt** [comment]
Seems to be resolved or... at least as of v1.0.3 @vinzv ?

**Comment by vinzv** [comment]
Yup, done! 🍻
