### ISSUE TITLE
[Elementary OS 5 or 6]Change profile always switch back to default in a few seconds

### ISSUE THREAD

**Issue by augustoicaro** [tuxedocomputers/tuxedo-control-center#162]
Hi,

I have a MAG-15 running elementary OS 6 with Control Center 1.1.1 and I create I custom profile for max performance, but every time that I open the system tray menu the profile is switched to default, even if global profile options are disabled. Also, I got another bug in app profile menu that after setting my custom profile as main and battery profile, I can't set any other as main or battery profile (save button don't work). Can you confirm if it is a general bug or just in my machine?

I also read the issues and one thing that may be related to my problem is when I select a profile in the custom tray, the system doesn't prompt me to type the password. I checked the output while running the control center in the terminal, but I got no output.

My workaround for while is as this new profile is set as main and battery profile when I restart `tccd` my profile is activated until I open the system tray menu.

I will work to fix these 2 problems in my spare time and submit a PR when it is done.

**Comment by tuxedoxt** [comment]
Hello,

the "save assignment doesn't work on profile overview" bug is known, broken in the last version will soon be updated.

To my knowledge however, the tray functionality works. For the profile switch in tray no password is necessary. It switches profile to the chosen one until a "normal state change" (like plugging or unplugging power) happens. On state change it will be changed to the assigned profile.

**Comment by augustoicaro** [comment]
Oh! Great.

So, I think the problem is the battery charger limiter that I set to 60% on windows(that change in bios) and maybe it is always changing the "normal state" when is "full charged".

I will give a feedback about it later.

**Comment by augustoicaro** [comment]
Ok, I did a rapid test here with ac unplugged and the problem persists. Every time that I set a profile, 2 seconds later it's switched back to default.

I'm familiar with typescript and I explored the code yesterday, I think that I'm able to debug the code and fix the problem for me. Also, this problem can be a wingpanel problem (system related). Any tips bout debugging?

I will keep you updated.

**Comment by augustoicaro** [comment]
Yes, is confirmed. It is a bug with the elementary OS community system indicator manager(They had removed the system indicators feature since version 5 Juno). So I see a few options for me right now:

1. Implement a profile selector in the main app
2. Change the system tray menu implementation to just select a profile and close without the radio option (This can solve my problem, but isn't the best approach)
3. Use [Brunoais' profile changer](https://github.com/brunoais/tuxedo-control-center-profile-changer/tree/master) to switch my profiles manually.

I tested option 3 and it is working as expected. I need to keep the tcc closed or I get the same problem of switching back to the default profile (For sure it is an event action after changing the profile that switches back to default profile).

As it is a system related problem and for me the workaround is good, I will close this issue and update the issue title.

Thanks for your help :)

**Comment by tuxedoxt** [comment]
I am not sure I understood it correctly. You mean it's tray functionality related?

What can be observed with `journalctl -u tccd -f` when the tray is used to switch profiles?

**Comment by augustoicaro** [comment]
> I am not sure I understood it correctly. You mean it's tray functionality related?
Not the app tray functionality, but Elementary OS 5 and 6 tray functionality. By default, they removed the tray feature and only show system indicators provided by them. There is a community package from older OS versions that reenable this feature, but this package is poorly maintained and there are a few bugs like the one that I'm facing.

> What can be observed with journalctl -u tccd -f when the tray is used to switch profiles?
```
Hint: You are currently not seeing messages from other users and the system.
      Users in groups 'adm', 'systemd-journal' can see all messages.
      Pass -q to turn off this notice.
-- Logs begin at Mon 2021-12-06 08:24:42 PST. --
```

I'm positive that it is a system related problem and not a TCC bug.

**Comment by tuxedoxt** [comment]
Hmm for the journalctl command you might need sudo on your system.

> Not the app tray functionality, but Elementary OS 5 and 6 tray functionality. By default, they removed the tray feature and only show system indicators provided by them. There is a community package from older OS versions that reenable this feature, but this package is poorly maintained and there are a few bugs like the one that I'm facing.

Oh if they only allow indicators and disable the click events, sure. Sounds weird for standard tray functionality though..

**Comment by augustoicaro** [comment]
> Hmm for the journalctl command you might need sudo on your system.
```
-- Logs begin at Mon 2021-12-06 08:19:41 PST. --
Dec 07 12:17:09 BeBop tccd[13720]: Daemon is stopped
Dec 07 12:17:09 BeBop systemd[1]: tccd.service: Succeeded.
Dec 07 12:17:09 BeBop systemd[1]: Stopped TUXEDO Control Center Service.
-- Reboot --
Dec 07 12:17:56 BeBop systemd[1]: Started TUXEDO Control Center Service.
Dec 07 12:17:56 BeBop tccd[959]: Starting daemon v1.1.1 (node: v10.15.3 arch: x64)
Dec 07 12:17:56 BeBop tccd[959]: tuxedo-io ver 0.2.4 [ interface: uniwill ]
Dec 07 12:17:56 BeBop tccd[959]: Additional ycbcr420Workaround card in settings
Dec 07 12:17:56 BeBop tccd[959]: Filled missing settings with default: /etc/tcc/settings <--- Was Cool and breezy and after right click on the tray icon it changed.
Dec 07 12:17:56 BeBop tccd[959]: Set display brightness to 6% (1440) on intel_backlight
Dec 07 12:17:57 BeBop tccd[959]: Daemon started
Dec 07 12:21:13 BeBop tccd[959]: StateSwitcherWorker: Temp profile "Default" selected <--- Same here
Dec 07 12:21:13 BeBop tccd[959]: Set display brightness to 6% (1440) on intel_backlight
Dec 07 12:21:29 BeBop tccd[959]: StateSwitcherWorker: Temp profile "Work" selected <--- Clicked in my custom profile
Dec 07 12:21:29 BeBop tccd[959]: Set display brightness to 6% (1440) on intel_backlight
Dec 07 12:21:32 BeBop tccd[959]: StateSwitcherWorker: Temp profile "Default" selected <--- Few seconds later auto switch back
Dec 07 12:21:32 BeBop tccd[959]: Set display brightness to 6% (1440) on intel_backlight
```
> Oh if they only allow indicators and disable the click events, sure. Sounds weird for standard tray functionality though..

They have a minimalistic philosophy and this decision of removing the indicators feature is controversial in the community. So, there is no standart tray functionality. This is why exists this community system tray package(buggy), it's to enable 3rd party indicators.

**Comment by tuxedoxt** [comment]
Errm so the click events happen. Actual profile switch occurs but the tray functionality "auto selects" the previously selected and generates a new click for the option as if the user switched back!?!?

**Comment by augustoicaro** [comment]
> Errm so the click events happen. Actual profile switch occurs but the tray functionality "auto selects" the previously selected and generates a new click for the option as if the user switched back!?!?

Yep. Super weird. This only happens for this radio menu selectors. For sure it is a community's system tray package bug. 

The Brunoais' profile changer has been very handy as workaround for this problem :)
