### ISSUE TITLE
Add Flatpak support

### ISSUE THREAD

**Issue by ale03068** [tuxedocomputers/tuxedo-control-center#17]
Hi, is possible to add your app to Flathub? I find handy to install gui apps this way, without adding four repositories.

P.S. I found your software from these video/article
https://www.youtube.com/watch?v=6A5MCK74YEg
https://www.forbes.com/sites/jasonevangelho/2020/04/28/get-control-of-your-linux-laptop-with-tuxedo-control-center/#436efaac6921

**Comment by vinzv** [comment]
> is possible to add your app to Flathub? I find handy to install gui apps this way, 

Thanks for suggesting this. We'll have a look into it.

> without adding four repositories.

Tbh there's no need to add all four. The `deb.tuxedocomputers.com` is enough if you just want to use TCC.

**Comment by AleSprea97** [comment]
Thank you for the answer, I appreciate it.
I tried adding "deb.tuxedocomputers.com" following this tutorial (https://www.tuxedocomputers.com/en/Infos/Help-and-Support/Instructions/Add-TUXEDO-Computers-software-package-sources.tuxedo#)  but I get an error:

1)Select »Software & Updates« from the main menu/dashboard and switch to the »Other Software« tab.
Select "Add ..." and enter the following as APT line.
deb http://deb.tuxedocomputers.com/ubuntu[focal] main

2)sudo wget -O - http://deb.tuxedocomputers.com/0x54840598.pub.asc | sudo apt-key add -

--2020-05-01 19:47:02--  http://deb.tuxedocomputers.com/0x54840598.pub.asc
Risoluzione di deb.tuxedocomputers.com (deb.tuxedocomputers.com)... 88.99.148.10
Connessione a deb.tuxedocomputers.com (deb.tuxedocomputers.com)|88.99.148.10|:80... connesso.
Richiesta HTTP inviata, in attesa di risposta... 200 OK
Lunghezza: 3140 (3,1K) [text/plain]
Salvataggio in: "STDOUT"

 100%[===========================>]   3,07K  --.-KB/s    in 0,001s  

2020-05-01 19:47:02 (4,21 MB/s) - scritto su stdout [3140/3140]

3)sudo apt-key adv --fingerprint 54840598

Executing: /tmp/apt-key-gpghome.bWmX47PY0J/gpg.1.sh --fingerprint 54840598
pub   rsa4096 2016-05-12 [SC]
      E5D0 C320 BBCE 8D21 CDF6  0DD5 120E D28D 5484 0598
uid           [  non nota  ] TUXEDO Computers GmbH (www.tuxedocomputers.com) <tux@tuxedocomputers.com>
sub   rsa4096 2016-05-12 [E]

4)sudo apt update
E: Voce 49 non corretta nel file list (/etc/apt/sources.list Component)
E: Impossibile leggere l'elenco dei sorgenti.

I think that something goes wrong in point 3: "uid unknown" (uid non nota)
P.S. Excuse me but the terminal output are in part in Italian.

**Comment by AleSprea97** [comment]
Thank you for the answer, I appreciate it.
I tried adding "deb.tuxedocomputers.com" following this tutorial (https://www.tuxedocomputers.com/en/Infos/Help-and-Support/Instructions/Add-TUXEDO-Computers-software-package-sources.tuxedo#)  but I get an error:

1)Select »Software & Updates« from the main menu/dashboard and switch to the »Other Software« tab.
Select "Add ..." and enter the following as APT line.
deb http://deb.tuxedocomputers.com/ubuntu[bionic] main

2)sudo wget -O - http://deb.tuxedocomputers.com/0x54840598.pub.asc | sudo apt-key add -

--2020-05-01 19:47:02--  http://deb.tuxedocomputers.com/0x54840598.pub.asc
Risoluzione di deb.tuxedocomputers.com (deb.tuxedocomputers.com)... 88.99.148.10
Connessione a deb.tuxedocomputers.com (deb.tuxedocomputers.com)|88.99.148.10|:80... connesso.
Richiesta HTTP inviata, in attesa di risposta... 200 OK
Lunghezza: 3140 (3,1K) [text/plain]
Salvataggio in: "STDOUT"

 100%[===========================>]   3,07K  --.-KB/s    in 0,001s  

2020-05-01 19:47:02 (4,21 MB/s) - scritto su stdout [3140/3140]

3)sudo apt-key adv --fingerprint 54840598

Executing: /tmp/apt-key-gpghome.bWmX47PY0J/gpg.1.sh --fingerprint 54840598
pub   rsa4096 2016-05-12 [SC]
      E5D0 C320 BBCE 8D21 CDF6  0DD5 120E D28D 5484 0598
uid           [  non nota  ] TUXEDO Computers GmbH (www.tuxedocomputers.com) <tux@tuxedocomputers.com>
sub   rsa4096 2016-05-12 [E]

4)sudo apt update
E: Voce 49 non corretta nel file list (/etc/apt/sources.list Component)
E: Impossibile leggere l'elenco dei sorgenti.

I think that something goes wrong in point 3: "uid unknown" (uid non nota)
P.S. Excuse me but the terminal output are in part in Italian.

**Comment by vinzv** [comment]
This is where the error roots from:

> 1)Select »Software & Updates« from the main menu/dashboard and switch to the »Other Software« tab.
> Select "Add ..." and enter the following as APT line.
> deb [http://deb.tuxedocomputers.com/ubuntu[bionic]](http://deb.tuxedocomputers.com/ubuntu%5Bbionic%5D) main

Leave out the square brackets […] and add another space character. For Ubuntu 18.04 the URL should look like this:
`deb http://deb.tuxedocomputers.com/ubuntu bionic main`

For Ubuntu 20.04 accordingly:
`deb http://deb.tuxedocomputers.com/ubuntu focal main`

**Comment by AleSprea97** [comment]
Thanks, with this modification now I installed correctly.
Unintentionally I proved that for noobs is better download software from some store than setup a repo LOL.
Unfortunately the fan control "is not supported on your model" :\

**Comment by nigelwarning** [comment]
Manjaro has this software in the official repositories. It would be nice to see this also for Arch Linux.
A lot of the Tuxedo software already is in the AUR. I hope someone would do this too for the Tuxedo Control Center, because it is really good.

**Comment by d4g** [comment]
I‘d also like to see flatpak and/or appImage support.

**Comment by StevenSeifried** [comment]
@nigelwarning TCC is back in the [AUR](https://aur.archlinux.org/packages/tuxedo-control-center/)

**Comment by nigelwarning** [comment]
@StevenSeifried Great! Thanks :D

**Comment by nickma82** [comment]
What's the status on this? Could this ticket be closed? Best, Nick

**Comment by alatiera** [comment]
There isn't much point in trying to flatpak this since there's a daemon with elevated privileges that needs to be run on the host anyway.

**Comment by vinzv** [comment]
We're most likely not making a Flatpak, therefore I'm closing this issue.

As always, feel free to reopen or add any comments.

**Comment by kpbearfl** [comment]
thinking about moving to OpenSUSE MicroOS, TCC as a flatpak would really be perfection
