### ISSUE TITLE
npm run build error:0308010C:digital envelope routines::unsupported

### ISSUE THREAD

**Issue by daschaich** [tuxedocomputers/tuxedo-control-center#172]
I'll say up front that I've never before had `npm` inflicted on me, so this may be an issue with my `Node.js` (v17.3.0) setup rather than `tcc`.  In that case, I hope it may be quick and easy for someone here to diagnose.  A couple days of Google searching have not given me any helpful hints.

I'm trying to set up `tcc` to gain control over fan speeds in slackware-current running on a TUXEDO InfinityBook S 15 - Gen6.  ([At present](http://www.slackware.com/changelog/current.php?cpu=x86_64) slackware-current is rc3 for slackware-15.0, with kernel 5.15.14.)  I have `tuxedo_keyboard` up and running:
```
$ lsmod | grep tux
tuxedo_io              16384  0
tuxedo_keyboard        40960  2 clevo_acpi,tuxedo_io
sparse_keymap          16384  2 intel_hid,tuxedo_keyboard
```
However, `sensors-detect` from `lm_sensors` v3.6.0 is unable to find any fan info, which I hope `tcc` will help with.

I attach the output of `npm run build`, which reports error:0308010C:digital envelope routines::unsupported at the build-ng stage.  Although `npm run build-electron` seems to run happily and `npm run test-common` reports "44 specs, 0 failures", `npm run start` says it is "Unable to find Electron app".  I see the same behavior from both the master branch at commit fbedcb3 and the release branch at commit e0f7efc (v1.1.2).  Google-inspired experiments with `--legacy-peer-deps`, `--force` and `npx -p npm@6` have not yet helped.  My `npm` is v8.3.0, libudev is v1.6.3.  [Edit to add: `npm` v8.3.2 hits the same error, as does `Node.js` v17.4.0.]

Thanks in advance for any suggestions or advice; let me know if any further diagnostics would be useful.

[build.log](https://github.com/tuxedocomputers/tuxedo-control-center/files/7877104/build.log)

**Comment by daschaich** [comment]
Trying again, I continue to hit this issue with commit e779d39, `npm` v8.18.0, `Node.js` v18.7.0 and kernel 5.15.38 in slackware-15.0.

**Comment by daschaich** [comment]
One last update to say that [tuxedo-fancontrol](https://git.42l.fr/neil/tuxedo-fancontrol)  has helped me get a handle on fan speeds, so I'm not going to keep trying to set up `tcc`.  At least for now I'll leave this issue open in case anyone knows what's up with `npm`.

**Comment by yochananmarqos** [comment]
They use Node 14, but I still can't get it to build, either. You might try with that.  They're also using Electron 13 which has been EOL for quite some time now.

```
nvm install 14
npm install
npm run build
```

[build.log](https://github.com/tuxedocomputers/tuxedo-control-center/files/10421598/build.log)

**Comment by yochananmarqos** [comment]
@daschaich I've edited my post above several times, so this just to let you know the notifications / emails you may have received with my previous edits are obsolete.
