### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by squalou** [tuxedocomputers/tuxedo-control-center#174]
Hi,

I'm trying to install TCC on a Tuxedo Infinitybook pro 14 Gen6.

I'm running an Ubuntu 21.10 "impish". (log story short : have to try different distribs, this one is popOs to tell the whole story)

When starting the service I get 

segmentation fault (core dumped)  ./dist/tuxedo-control-center/data/service/tccd

I do have other kernel modules installed

```
$ lsmod | ag tux  
tuxedo_io              20480  0
tuxedo_keyboard        45056  3 tuxedo_io,uniwill_wmi,clevo_wmi
sparse_keymap          16384  3 intel_hid,asus_wmi,tuxedo_keyboard
```

Is there anything I can do to track / debug what happens ?

Sidenote : is there *any* way to control the fan speed with other means than TCC ?

**Comment by tuxedoxt** [comment]
Hello,

haven't seen a segfault for TCC yet. Did you install the deb package from our repo?

**Comment by squalou** [comment]
I tried but could not.
I filled in the repos configuration in /etc/apt/sources.list.d/ .... as explained on your ebsite instructions
BUT
no package is proposed for my os release (impish)

**Comment by tuxedoxt** [comment]
Ah, well you can always download the packages and install.

For example:
- http://deb.tuxedocomputers.com/ubuntu/pool/main/t/tuxedo-control-center/
- http://deb.tuxedocomputers.com/ubuntu/pool/main/t/tuxedo-keyboard/

**Comment by squalou** [comment]
It works ! 
sometimes good old solutions work best :)

closing and thank you !!
