### ISSUE TITLE
Tuxedo Control Center show "model not supported"

### ISSUE THREAD

**Issue by tzaspel-finatix** [tuxedocomputers/tuxedo-control-center#189]
Hey there,

after release 1.1.3 I try Fedora 35 on my Tuxedo Infinitybook S15 Gen6. I read a tweet that all dependencies are fulfilled now. So, I added the openSuse 15.3 repository to my Fedora Client and Install the TCC. 

Thereafter, I opened the Control Center, and it shows me, that my model isn't supported:
![TuxedoControlCenter](https://user-images.githubusercontent.com/90749078/162674970-9071f74e-8d9d-4726-8a9c-10693ee94ac1.png)

I have done something wrong? Maybe one hint. I have installed the Fedora operating system on a USB stick, but in my opinion this should not cause the problem.

**Comment by tuxedoxt** [comment]
Hello,

most likely an issue with the driver installation `tuxedo-keyboard` package. If you didn't already, try a restart. Otherwise `dkms status`, compare with `uname -r` to check if the driver got installed for your running kernel.

**Comment by tzabbi** [comment]
Thanks for your advices. It seems, that the driver for `tuxedo-keyboard` are not installed:
![tuxedo-control-center](https://user-images.githubusercontent.com/40226087/163133119-31e3d176-4582-4756-8831-18d866715666.png)

I installed the TCC with: `sudo dnf install tuxedo-control-center`
Should I manually install `tuxedo-keyboard` via dkms?

**Comment by tzaspel-finatix** [comment]
Thanks for your advice. It seems that the the `tuexdo-keyboard` is not installed:
![tuxedo-control-center](https://user-images.githubusercontent.com/90749078/163134856-eb75e1b9-5bbe-4d4b-bf62-eebc004bb64f.png)

I installed the TCC with `sudo dnf install tuxedo-control-center`

Should I install it manually via dkms?

**Comment by tuxedoxt** [comment]
Ok, that means package is installed but (for some reason) it's not build and installed dkms-wise. Usually there's some log (`/var/lib/dkms/tuxedo-keyboard`) if it failed. You can also attempt to manually retry it.

```
sudo dkms install tuxedo-keyboard/3.0.9
```

If it fails check error messages. In many cases kernel headers package is missing and need to be installed for the kernel you are using.

**Comment by tzaspel-finatix** [comment]
Can't find any logs in `/var/lib/dkms/tuxedo-keyboard`.

It looks like a issue with Fedora 35?
![linux-kernel-headers](https://user-images.githubusercontent.com/90749078/164162122-f733f73d-d172-4bd0-b55c-865ffb529d58.png)

**Comment by tuxedoxt** [comment]
> Can't find any logs in `/var/lib/dkms/tuxedo-keyboard`.
> 
> It looks like a issue with Fedora 35? ![linux-kernel-headers](https://user-images.githubusercontent.com/90749078/164162122-f733f73d-d172-4bd0-b55c-865ffb529d58.png)

Yeah seems like the header package installed version `5.16.5` headers and you are running `5.16.18` or something. You'll need the kernel headers for the currently running kernel `uname -r`.

**Comment by sheeepdev** [comment]
I also had the same problem on Fedora 36, and I fixed it by installing the `kernel-devel` package and restarting

**Comment by mandavister** [comment]
I had the exact same issue. Rebooting did the trick for me tough.
