### ISSUE TITLE
ACPI error, can't shutdown and computer freezes

### ISSUE THREAD

**Issue by Rafael000000** [tuxedocomputers/tuxedo-control-center#193]
At least once a week, I've had a max of three times a week, my system freezes (sort of). I can't do anything else then choose for reboot or shutdown. But at shutdown I get the following error (Retrieved from journalctl): 

> May 05 10:53:10 hello-today kernel: clevo_acpi: failed to evaluate _DSM
May 05 10:53:13 hello-today kernel: ACPI Error: AE_TIME, Returned by Handler for [EmbeddedControl] (20211217/evregion-291)
May 05 10:53:13 hello-today kernel: ACPI Error: Timeout from EC hardware or EC device driver (20211217/evregion-301)
May 05 10:53:13 hello-today kernel: ACPI Error: Aborting method \_SB.DCHU.ZEVT due to previous error (AE_TIME) (20211217/psparse-529)
May 05 10:53:13 hello-today kernel: ACPI Error: Aborting method \_SB.DCHU._DSM due to previous error (AE_TIME) (20211217/psparse-529)
May 05 10:53:13 hello-today kernel: ACPI: \_SB_.DCHU: failed to evaluate _DSM (0x11)
May 05 10:53:13 hello-today kernel: clevo_acpi: failed to evaluate _DSM
May 05 10:53:13 hello-today tccd[228323]: /snapshot/tuxedo-control-center/node_modules/dbus-next/lib/connection.js:139
May 05 10:53:13 hello-today tccd[228323]:         throw new Error('Cannot send message, stream is closed');
May 05 10:53:13 hello-today tccd[228323]:         ^
May 05 10:53:13 hello-today tccd[228323]: Error: Cannot send message, stream is closed
May 05 10:53:13 hello-today tccd[228323]:     at EventEmitter.message (/snapshot/tuxedo-control-center/node_modules/dbus-next/lib/connection.js:139:15)
May 05 10:53:13 hello-today tccd[228323]:     at MessageBus.send (/snapshot/tuxedo-control-center/node_modules/dbus-next/lib/bus.js:371:22)
May 05 10:53:13 hello-today tccd[228323]:     at EventEmitter.<anonymous> (/snapshot/tuxedo-control-center/node_modules/dbus-next/lib/bus.js:153:14)
May 05 10:53:13 hello-today tccd[228323]:     at EventEmitter.emit (events.js:315:20)
May 05 10:53:13 hello-today tccd[228323]:     at /snapshot/tuxedo-control-center/node_modules/dbus-next/lib/connection.js:116:14
May 05 10:53:13 hello-today tccd[228323]:     at Socket.<anonymous> (/snapshot/tuxedo-control-center/node_modules/dbus-next/lib/message.js:63:9)
May 05 10:53:13 hello-today tccd[228323]:     at Socket.emit (events.js:315:20)
May 05 10:53:13 hello-today tccd[228323]:     at emitReadable_ (_stream_readable.js:562:12)
May 05 10:53:13 hello-today tccd[228323]:     at processTicksAndRejections (internal/process/task_queues.js:83:21)
May 05 10:53:13 hello-today systemd[1]: tccd.service: Main process exited, code=exited, status=1/FAILURE
May 05 10:53:13 hello-today systemd[1]: tccd.service: Failed with result 'exit-code'.

I searched around but I couldn't find a solution. Is there a solution for this error?

Edit:

I am running:
OS: ArchLabs Linux
Kernel: 5.17.5-zen1-1-zen

**Comment by tuxedoxt** [comment]
Hello sorry for late answer, if your problem persists you need to update the EC.

I'll close for now.

If the problem persists after update please write your model.
