### ISSUE TITLE
1.1.5 causes massive freezes

### ISSUE THREAD

**Issue by antoscha** [tuxedocomputers/tuxedo-control-center#215]
Hello,

Something is wrong with 1.1.5, it makes my system behave unlike 1.1.4: booting takes unusually long time, sound becomes intermittent, and the process `tccd` constantly consumes about 35% CPU time. After killing `tccd` the system gets back to normal, and I had to downgrade to 1.1.4.

Parameters:
Laptop Tuxedo InfinityBook S 15 Gen6
OS Arch Linux
Package https://aur.archlinux.org/packages/tuxedo-control-center-bin

**Comment by vinzv** [comment]
Closing obsolete. Please check with a recent version again and feel free to open a new issue.

Thanks!
