### ISSUE TITLE
1.1.6 Bug: custom profile with reduced CPUs filles the system log

### ISSUE THREAD

**Issue by temirg** [tuxedocomputers/tuxedo-control-center#218]
** Environment **
System:
  Host: work17 Kernel: 5.19.2-1-default arch: x86_64 bits: 64, Distro: openSUSE Tumbleweed 20220828
Machine:
  Type: Laptop System: SchenkerGmbH product: SCHENKER WORK (Early 2021)    v: N/A serial: N/A
  Mobo: NB01 model: NS50_70MU serial: N/A UEFI: INSYDE v: 1.07.15NRTR2     date: 04/11/2022
CPU:
  Info: quad core model: 11th Gen Intel Core i5-11300H bits: 64 type: MT MCP   cache: L2: 5 MiB
  Speed (MHz): avg: 3100 min/max: 400/4400 cores: 1: 3100 2: 3100 3: 3100  4: 3100 5: 3100 6: 3100 7: 3100 8: 3100
**************

tccd with a custom profile (6 of 8 cores active) created to get the notebook silent and cool fills the system log with messages:

CpuWorker: Error validating/reapplying profile => Error: Could not read value from path: 
/sys/devices/system/cpu/cpu6/cpufreq/cpuinfo_min_freq => Error: EBUSY: resource busy or locked, read

Enabling cores 6-7 via "sudo chcpu -e 6-7" results in:

Aug 29 20:12:26 work17 kernel: smpboot: Booting Node 0 Processor 6 APIC 0x5
Aug 29 20:12:26 work17 kernel: smpboot: Booting Node 0 Processor 7 APIC 0x7
Aug 29 20:12:28 work17 tccd[740]: CpuWorker: onlineCores not as expected, 8 instead of 6
Aug 29 20:12:28 work17 tccd[740]: CpuWorker: Incorrect settings, reapplying profile
Aug 29 20:12:28 work17 kernel: smpboot: CPU 6 is now offline
Aug 29 20:12:28 work17 kernel: smpboot: CPU 7 is now offline
Aug 29 20:12:31 work17 tccd[740]: CpuWorker: Error validating/reapplying profile => Error: Could not read value from path: /sys/devices/system/cpu/cpu6/cpufreq/c
puinfo_min_freq => Error: EBUSY: resource busy or locked, read

tccd should know: core count is limited from TCC and not clutter up the log.

Regards, temir.

**Comment by temirg** [comment]
**Update:**
TCC 1.1.7 - the problem persists.

Regards, temir.

**Comment by gary094** [comment]
Just wanted to chime in and say that I have the same issue. Every couple of seconds I get logs like this in my journalctl:

```
Oct 15 12:55:59 ibs tccd[16278]: CpuWorker: Error validating/reapplying profile => Error: Could not read value from path: /sys/devices/system/cpu/cpu4/cpufreq/cpuinfo_min_freq => Error: EBUSY: resource busy or locked, read
Oct 15 12:56:02 ibs tccd[16278]: CpuWorker: Error validating/reapplying profile => Error: Could not read value from path: /sys/devices/system/cpu/cpu4/cpufreq/cpuinfo_min_freq => Error: EBUSY: resource busy or locked, read
Oct 15 12:56:05 ibs tccd[16278]: CpuWorker: Error validating/reapplying profile => Error: Could not read value from path: /sys/devices/system/cpu/cpu4/cpufreq/cpuinfo_min_freq => Error: EBUSY: resource busy or locked, read
Oct 15 12:56:08 ibs tccd[16278]: CpuWorker: Error validating/reapplying profile => Error: Could not read value from path: /sys/devices/system/cpu/cpu4/cpufreq/cpuinfo_min_freq => Error: EBUSY: resource busy or locked, read
Oct 15 12:56:11 ibs tccd[16278]: CpuWorker: Error validating/reapplying profile => Error: Could not read value from path: /sys/devices/system/cpu/cpu4/cpufreq/cpuinfo_min_freq => Error: EBUSY: resource busy or locked, read
Oct 15 12:56:14 ibs tccd[16278]: CpuWorker: Error validating/reapplying profile => Error: Could not read value from path: /sys/devices/system/cpu/cpu4/cpufreq/cpuinfo_min_freq => Error: EBUSY: resource busy or locked, read
Oct 15 12:56:17 ibs tccd[16278]: CpuWorker: Error validating/reapplying profile => Error: Could not read value from path: /sys/devices/system/cpu/cpu4/cpufreq/cpuinfo_min_freq => Error: EBUSY: resource busy or locked, read
Oct 15 12:56:20 ibs tccd[16278]: CpuWorker: Error validating/reapplying profile => Error: Could not read value from path: /sys/devices/system/cpu/cpu4/cpufreq/cpuinfo_min_freq => Error: EBUSY: resource busy or locked, read
Oct 15 12:56:23 ibs tccd[16278]: CpuWorker: Error validating/reapplying profile => Error: Could not read value from path: /sys/devices/system/cpu/cpu4/cpufreq/cpuinfo_min_freq => Error: EBUSY: resource busy or locked, read
Oct 15 12:56:26 ibs tccd[16278]: CpuWorker: Error validating/reapplying profile => Error: Could not read value from path: /sys/devices/system/cpu/cpu4/cpufreq/cpuinfo_min_freq => Error: EBUSY: resource busy or locked, read

```

**Comment by vinzv** [comment]
Closing obsolete. Please check with a recent version again and feel free to open a new issue.

Thanks!
