### ISSUE TITLE
Cpu frequecy does not match with the cpu

### ISSUE THREAD

**Issue by Tructruc** [tuxedocomputers/tuxedo-control-center#219]
Hi, I'm using Tuxedo Control Center 1.1.5 on my tuxedo pulse 15 gen 2.

The min frequency show in the setting as 5.4ghz or my cpu isn't rated for that and it never achieve this, the real minimum is about 400mhz. So I cannot set it as I want.

Here is a screen capture of it showing this on one of my custom profile.
![image](https://user-images.githubusercontent.com/46050049/190690240-82bb3fbc-21cf-41ab-837e-6117841d0f54.png)

But on the default profile it really shows 0.4ghz
![image](https://user-images.githubusercontent.com/46050049/190690611-e313922e-1a1a-4a91-b0be-3cd302405ca5.png)

And even if I try to duplicate of of the default profiles it says 5.4ghz.

Thanks in advance for your help.
Tructruc00

**Comment by tuxedoxt** [comment]
Hello,

this was a GUI bug that appeared with the `amd-pstate` driver.

It should now be fixed as of v1.2.1. Also with the new driver in the kernel, frequency settings are more fine-grained for these AMD devices.

If there are still issues feel free to reopen.
