### ISSUE TITLE
Fans are set at the same speed (or the highest of all fan speeds)

### ISSUE THREAD

**Issue by enriquezmark36** [tuxedocomputers/tuxedo-control-center#222]
Hello, 

I am currently using a Gigabyte G5 GD. I use Tuxedo Control Center 1.1.7 to configure the performance profiles and the fans which works given that G5 GD uses a chassis from Clevo. 
All the exposed features seem to work well (I doubt about the System Profiles is working though).

There is one thing I noticed. Compared to Windows 11 (the preinstalled OS), the fans are unusually running at the same speed. In Windows 11, the fan speeds are independent. 

The Fan Profile selected is the Freezy, which gives the GPU Fan a head start (i.e., higher speed by comparison with the CPU fan at the same temperature). Yet in any temperature, the GPU and CPU Fans are always operating at the same speed. Even if I ran only a GPU-only load, while the CPU is mostly idle, both fans are nearly at the max speed.

Based on the code, it seems to be deliberate that both are set to the same speed. The comment, however, implies that a decision logic should be present there and that 'uniwill devices' must always be at the same speed. But as of 1.1.7, it is just hard coded to be the same speed.

src/service-app/classes/FanControlWorker.ts:94
``` typescript
        // Decide on a fan control approach
        // Per default fans are controlled using the 'same speed' approach setting the same speed for all fans chosen
        // from the max speed decided by each individual fan logic
        // Using the 'same speed' approach is necessary for uniwill devices since the fans on some
        // devices can not be controlled individually.
        this.modeSameSpeed = true;
```

I think there should be a way to set the fan speeds independently (if supported) so that we can make these devices 'noise-efficient' . 

P.S. I suppose getModuleInfo() can be used to differentiate between Clevo and Uniwill devices, then set the modeSameSpeed flag to true if it is a Uniwill device?
P.S. 2 Since the heat pipes are probably shared between the GPU and CPU Fans, a hot GPU will also warm up the CPU causing the CPU Fan to ramp up (eventually). The CPU Fan is noisy AF so I'd prefer the GPU Fan to max out before the CPU Fan.

Thanks.

**Comment by tuxedoxt** [comment]
Hello,

in short, this is by design.

The comment in the code reflect one necessary case from the past. If you look back further you would see that it was actually separated depending on device. However, with a later decision fans were set to always track the same value.

Main reason for this was that in all TUXEDO models the cooling system between CPU and GPU is connected, in many cases with heat pipes. For example, this should allow both fans to cool the CPU even when the GPU is not in use.
