### ISSUE TITLE
Minimum Fan Speed has no effect

### ISSUE THREAD

**Issue by QBrunner** [tuxedocomputers/tuxedo-control-center#225]
Minimum Fan Speed has no effect, unless the fan is already on due to the regular fan curve. 

Expected: When Minimum Fan Speed is set to a value the fans should always spin at least at this value, like seen in the fan curve.
Actual Result: The Fans do not spin, unless the fan curve is above the minimum fan speed for the given temperature.

Kernel: 5.15.72-1-lts
Init System: Systemd
OS: Arch Linux
TCC-Version: 1.1.8 downloaded as rpm package from the aur
Laptop: Tuxedo Pulse 15 Gen1

![FanCurve](https://user-images.githubusercontent.com/57155158/194769553-0d977491-26b3-4d75-9db3-1de12c0425af.png)
![FanSpeed](https://user-images.githubusercontent.com/57155158/194769554-b41c163f-b60d-45d3-be60-91ad7e8b604a.png)
![Service](https://user-images.githubusercontent.com/57155158/194769556-301cde31-c64c-418f-82a0-4f2c6bdb7858.png)

**Comment by Matombo** [comment]
did you also update tuxedo-keyboard?

**Comment by QBrunner** [comment]
Yes I did.

**Comment by matt-wirtz** [comment]
Yes, I have the same issue. It was working before updating to TC 1.1.8-1.

Kernel: 5.14.21-150400.22
Init System: Systemd
OS: OpenSUSE
TCC-Version: 1.1.8-1
Laptop: Tuxedo Pulse 14 Gen1

**Comment by Matombo** [comment]
does it work when you set it to at least 20%?

**Comment by Matombo** [comment]
also: does this also happen in the 1.2.0 release?

**Comment by QBrunner** [comment]
> does it work when you set it to at least 20%?

I have tried it with up to 100% and it didn't work.

**Comment by QBrunner** [comment]
> also: does this also happen in the 1.2.0 release?

Yes it works as intended again. Thank you!
