### ISSUE TITLE
Persist Profile Settings

### ISSUE THREAD

**Issue by matthias-Q** [tuxedocomputers/tuxedo-control-center#236]
Hi,
I am running a Tuxedo Pulse 14" and I cannot persist the profile settings. After each reboot or waking it up from suspend, it uses the default profile.
Therefore the fans are always spinning.

Is there a way to set a different default profile? Can I set these settings via kernel command or otherwise without having to use the control center (maybe automating it via a script)?

**Comment by tuxedoxt** [comment]
Hello,

you can only assign profiles through the GUI atm. You can set one profile to be used on battery and one when power is connected. To assign go to edit the profile you want and assign it to one or both of these states, hit save => type password. After this the profile should always be used in the chosen states.

**Comment by matthias-Q** [comment]
Thanks. got it working. I was missing the program that starts the graphical password prompt.
