### ISSUE TITLE
Battery profiling

### ISSUE THREAD

**Issue by LukashonakV** [tuxedocomputers/tuxedo-control-center#243]
Dear Tuxedo maintainers,
Is it possible to add such useful functionality as battery profiling as it realized for example in MSI laptops. The point is to provide 3 battery profiles like:

1. Battery life (prevent to charge the battery more than 60%). Such profile prolongs battery life cycle.
2. Balance (prevent to charge the battery more than 80%)
3. OnLine(battery can be fully charged - 100%) 

When "Battery life" is chosen with pluged AC adapter - laptop can work with the maximum performance but battery should be charged not more than 60%. When laptop is OFF or in sleep mode the same - battery profile should control the charging process.

Thank you
Hope to see this soon )

Have a good day :)

**Comment by tuxedoxt** [comment]
Hello,

which device do you have?

If available for your device as of v1.2.3 there are three charging profiles to choose from.

**Comment by silles79** [comment]
I just tried this, whatever profile I selected the battery just charged to 100%

Laptop: TUXEDO InfinityBook Pro 16 - Gen7 Max Performance Edition

do I need to update any kernel modules?
using
silles@tuxedo:~/projects$ modinfo tuxedo_io 
filename:       /lib/modules/6.1.0-0.2-liquorix-amd64/updates/dkms/tuxedo_io.ko.xz
alias:          wmi:ABBC0F6F-8EA1-11D1-00A0-C90629100000
alias:          wmi:ABBC0F6E-8EA1-11D1-00A0-C90629100000
alias:          wmi:ABBC0F6D-8EA1-11D1-00A0-C90629100000
alias:          wmi:ABBC0F6D-8EA1-11D1-00A0-C90629100000
alias:          acpi*:CLV0001:*
alias:          wmi:ABBC0F6D-8EA1-11D1-00A0-C90629100000
alias:          wmi:ABBC0F6B-8EA1-11D1-00A0-C90629100000
license:        GPL
version:        0.3.1
author:         TUXEDO Computers GmbH <tux@tuxedocomputers.com>
description:    Hardware interface for TUXEDO laptops
srcversion:     1F806CEBDC2235F81F3C547
depends:        tuxedo_keyboard
retpoline:      Y
name:           tuxedo_io
vermagic:       6.1.0-0.2-liquorix-amd64 SMP preempt mod_unload

**Comment by tuxedoxt** [comment]
tuxedo-keyboard v3.1.2

However if it is not updated and active you will not see the settings in TCC.

It is known that the max reported value adjusts at the end of the charging cycle though, so afterwards it will jump up to 100%. Unsure if we can readout the "original" max somewhere. This is under investigation.

**Comment by rustamzh** [comment]
Thanks a lot for this feature. However, I agree, it is super annoying when the charge limit can be only observed during battery benchmarking. @tuxedoxt, when exploring the driver, I was surprised that it does not follow already existing [sysfs api](https://www.kernel.org/doc/Documentation/ABI/testing/sysfs-class-power) with charge_control_{start,stop}_threshold and charge_full{,_design}, which btw is [well incorporated into KDE](https://forum.manjaro.org/uploads/default/original/3X/f/9/f92b9334198e442cc0bcbf43523300f790b01a01.png)

**Comment by LukashonakV** [comment]
> Hello,
> 
> which device do you have?
> 
> If available for your device as of v1.2.3 there are three charging profiles to choose from.

TUXEDO InfinityBook S 15 - Gen7

**Comment by LukashonakV** [comment]
So  I faced with the blocker issue now. Once tcc is updated to v.1.2.3 and tuxedo-keyboard is 3.1.2 the application has lost control even under CPU. Now even downgrade to v.1.2.2 and v.3.1.1 doesn't solve the issue :(
Dear developers kindly bring it back :)
![ps_2022-12-28-17_19_49](https://user-images.githubusercontent.com/23121044/209826053-d9c625aa-51fc-4a06-adc6-e489f357d99c.png)
![ps_2022-12-28-17_20_22](https://user-images.githubusercontent.com/23121044/209826057-f6635dac-6898-4d4d-a6fe-a3cb474332ed.png)
From the console the only issue is:
```
libva error: vaGetDriverNameByIndex() failed with unknown libva error, driver_name = (null)
```

**Comment by tuxedoxt** [comment]
> Thanks a lot for this feature. However, I agree, it is super annoying when the charge limit can be only observed during battery benchmarking. @tuxedoxt, when exploring the driver, I was surprised that it does not follow already existing [sysfs api](https://www.kernel.org/doc/Documentation/ABI/testing/sysfs-class-power) with charge_control_{start,stop}_threshold and charge_full{,_design}, which btw is [well incorporated into KDE](https://forum.manjaro.org/uploads/default/original/3X/f/9/f92b9334198e442cc0bcbf43523300f790b01a01.png)

Agreed, the reported charge level is very misleading. So far I haven't seen any way to readout the absolute maximum when on a profile with lower max. If you have any tips please let me know.

As for the existing sysfs interface the available options were considered but the feature does not correspond to any one of them well enough. The interface feature used does not allow threshold control other than per these predefined profiles. The `charge_type` property might be the most fitting, but would then also affect the threshold which would be quite the side-effect.

For a quick implementation it was placed as a platform specific config for now. If you have ideas how it could fit better or be integrated, feedback is always welcome.

**Comment by tuxedoxt** [comment]
> So I faced with the blocker issue now. Once tcc is updated to v.1.2.3 and tuxedo-keyboard is 3.1.2 the application has lost control even under CPU. Now even downgrade to v.1.2.2 and v.3.1.1 doesn't solve the issue :( Dear developers kindly bring it back :) ![ps_2022-12-28-17_19_49](https://user-images.githubusercontent.com/23121044/209826053-d9c625aa-51fc-4a06-adc6-e489f357d99c.png) ![ps_2022-12-28-17_20_22](https://user-images.githubusercontent.com/23121044/209826057-f6635dac-6898-4d4d-a6fe-a3cb474332ed.png) From the console the only issue is:
> 
> ```
> libva error: vaGetDriverNameByIndex() failed with unknown libva error, driver_name = (null)
> ```

Check

```
dkms status
uname -r
```

it should say "installed" for `tuxedo-keyboard` for your currently booted kernel.

If not try to reinstall tuxedo-keyboard package. Ex for ubuntu:

```
sudo apt install --reinstall tuxedo-keyboard
```

**Comment by LukashonakV** [comment]
So, I would predict you complain about my Gentoo system as Tuxedo company has done a couple of time. But from the system point of view there's not really big difference. 
What is I see now:

1. Clone https://github.com/tuxedocomputers/tuxedo-keyboard
2. make clean & make
3. sudo make install
4. In addition: goto /usr/src/linux + make modules_install
5. Reboot system
6. ```lsmod | egrep "clevo|tuxedo" ``` - get the loaded modules list
![ps_2023-01-09-15_29_23](https://user-images.githubusercontent.com/23121044/211309697-8950d879-024d-4153-a3c6-ae7aa25757c0.png)
7. Once modules are loaded I've got working keyboard functionality such as switch on/off keyboard backlight.
8. See modinfo attached: shows all necessary information about the loaded modules 
[modinfo.txt](https://github.com/tuxedocomputers/tuxedo-control-center/files/10373200/modinfo.txt)
9. ```uname -r``` : 5.15.80-gentoo-x86_64

**Comment by tuxedoxt** [comment]
Right, driver looks to be loaded.

Next step check tccd service log

```
journalctl -u tccd
```

and to be sure possibly that `/dev/tuxedo_io` exists (required for the fan features).


A little btw, I see you wrote that your device is "TUXEDO InfinityBook S 15 - Gen7". For this device OS control of charging features is not possible (it has "Flexicharger" option in BIOS settings however). Fan control should of course still work in TCC however.

**Comment by LukashonakV** [comment]
@tuxedoxt , thank you for your participation
In the screenshot:
1. On the right - /dev/tuxedo_io - exists
2. Gentoo uses OpenRC init system. But on the left terminal you can see the output of the tccd service. It says - ```FanControlWorker: Control unavailable```
![ps_2023-01-09-17_31_24](https://user-images.githubusercontent.com/23121044/211332125-c2957192-c625-466d-878f-f84058d82253.png)

**Comment by LukashonakV** [comment]
If it helps, the issue with the code block: FanControlWorker.ts
Line 107
```
        const fanCtrlUnavailableCondition = !TuxedoIOAPI.wmiAvailable() || this.fans.keys.length === 0;
        if (fanCtrlUnavailableCondition) {
            if (this.controlAvailableMessage === false) {
                this.tccd.logLine('FanControlWorker: Control unavailable');
            }
            this.controlAvailableMessage = true;
            return;
        } else {
            if (this.controlAvailableMessage === true) {
                this.tccd.logLine('FanControlWorker: Control resumed');
            }
            this.controlAvailableMessage = false;
        }

``` 
this.fans.keys.length is really equal to 0

**Comment by tuxedoxt** [comment]
Yeah I had a look, this is not part of the release version however, it is/was an unfixed bug in the master branch. Doesn't explain previous versions not working.

If you are looking for release versions the tags should be used. Latest release is currently also available in the release branch.

If you still want the non-released version the master branch should now also be patched and working ;)

**Comment by LukashonakV** [comment]
@tuxedoxt  thank you. Now it works well.
![ps_2023-01-10-15_12_50](https://user-images.githubusercontent.com/23121044/211548703-d76b7d8f-ba55-4840-9866-64396f05ba9d.png)
+ Yeah. Actually I can manage battery in BIOS... Issue can be closed then :)

**Comment by LukashonakV** [comment]
@tuxedoxt can you inspect all code for the same issue ? As I see for example there is the same method in CpuController.ts at line 128, 191...

**Comment by Uhter** [comment]
> A little btw, I see you wrote that your device is "TUXEDO InfinityBook S 15 - Gen7". For this device OS control of charging features is not possible (it has "Flexicharger" option in BIOS settings however). Fan control should of course still work in TCC however.

Hello @tuxedoxt,
Can you say us if the Battery profiling feature is possible on Polaris 17 AMD Gen3 (CZN)?
(Flexicharger option doesn't exist in BIOS)
