### ISSUE TITLE
Consider bigger gap between fan on and off than 1C

### ISSUE THREAD

**Issue by silles79** [tuxedocomputers/tuxedo-control-center#252]
However i configure the fan profile, this is whats happening:
1. Temp reaches fan off threshold, 
2. fan turns off. 
3. in the next 5 seconds, system heats by 1C 
4.  fans turns on start cooling down
5. goto 1

so fan keep being turn on and off every 10-15 seconds.

only workaround i found is to add a min fan speed. 

would be better to have a 5-10C gap between on and off if temp are low.
Looks like the gap is now 1C

**Comment by tuxedoxt** [comment]
Hello,

correct there is some filtering of sensor values but currently no hysteresis.

For now you could also try a different fan profile where the critical point is shifted.

**Comment by silles79** [comment]
i tried the few, but every time the critical point is seems to be around the fan off temp.
unless I configure it with extreme values.. like 30C off. or 65 on.

**Comment by tuxedoder** [comment]
Users now have the ability to create a custom fan curve for personalized fan behavior within tcc.
