### ISSUE TITLE
Support Aura 15 - Gen 2 battery stationary setting 

### ISSUE THREAD

**Issue by lescuer97** [tuxedocomputers/tuxedo-control-center#255]
is there any plan for getting some of the older laptops with this feature? I would love to have this on my as is always connected

**Comment by tuxedoxt** [comment]
Hello,

if you are referring to the recently released battery charging profiles feature this is unfortunately not available on the Aura. The Aura 15 Gen 2 has the "Flexicharger" setting in the BIOS settings instead. Albeit not exactly the same but similar feature.

**Comment by lescuer97** [comment]
> Hello,
> 
> if you are referring to the recently released battery charging profiles feature this is unfortunately not available on the Aura. The Aura 15 Gen 2 has the "Flexicharger" setting in the BIOS settings instead. Albeit not exactly the same but similar feature.

if I activate the Flexicharge setting and I set it to 80 on the stop charge. 
if I have it connected to the charger, does it affect the performance of the laptop?

**Comment by lescuer97** [comment]
thank you, I'll close this then if there is no plan to get this feature on the Aura 15
