### ISSUE TITLE
Only one fan running instead of both (Infinity Book Pro 14 Gen6)

### ISSUE THREAD

**Issue by stoll-it** [tuxedocomputers/tuxedo-control-center#256]
Tuxedo Control Center (v1.2.3) seems to not use the left fan on my Infinity Book Pro 14 Gen6 (BIOS N.1.15A12, EC 2.19.00.00, onboard graphics). Is that possible or am I testing it not as intended?

When I try to test the full fan power, only the right one runs. However, both run when I am in the BIOS setup.

Reproducible steps:

A) Turn on the device, open BIOS, wait 1-2 minutes. Both fans run lightly, e.g. a tissue stays hanging on both the left and right sides. This is as expected.

B) Start Tuxedo OS (uname -r: 5.15.0-10056-tuxedo), open Tuxedo Control Center, copy "TUXEDO Defaults" profile, select "Freezy" fan profile, minimum fan speed 100%, offset fan speed 100%, save the profile, select it from the context menu in the bottom right system tray.

Observation: After a few seconds, the right fan runs at full speed, the left one seems to not run at all.

Expectation: Both fans should run at full speed.

Please let me know if that's the wrong place to raise the issue.

**Comment by tuxedoxt** [comment]
> 

Hello,

more reliable would be to contact support, however, message received :) Both fans should be spinning, we'll have a look.

**Comment by Matombo** [comment]
Which exact model of the IBP 14 G6 do you have? U or H processor, With or without NVIDIA?

What is youzr current BIOS and EC version (can be looked up in bios settings)

**Comment by stoll-it** [comment]
@Matombo Thanks for your reply, my InfinityBook Pro 14 Gen6 has an i5-11300H processor (without NVIDIA, BIOS N.1.15A12, EC 2.19.00.00).

**Comment by Matombo** [comment]
Found the issue -> A fix sould hit the next version

**Comment by tuxedoxt** [comment]
Fix included in release v3.1.3

**Comment by stoll-it** [comment]
@Matombo @tuxedoxt Thank you! With the update (f99b283), both fans work on my machine.
