### ISSUE TITLE
Regression in fan control speed offset - 10% increment please

### ISSUE THREAD

**Issue by squalou** [tuxedocomputers/tuxedo-control-center#263]
Hi,

I've recently upgdated TCC (and bios and all) after one year without update.

With fan profile "Silent", and a fan speed offset of -10%, I used to manage to have the fan start spinning at around 60°,
and then it would only run at 10% speed.
Which is *very* silent and very comfortable.
For regular light workload it was perfect.

Now, whenever fan starts, it's always with 20% speed minimum, which is much louder. Every time it starts reminds me I should not update working things ;-)

Laptop is : TUXEDO InfinityBook Pro 14 Gen6 Standard
TCC 1.2.4
BIOS N.1.15A12 / EC 2.19.00

Would enjoy any help.

thx

**Comment by squalou** [comment]
in 
https://github.com/tuxedocomputers/tuxedo-control-center/blob/5683d72bb96ca215c715744b92613b98dc01218b/src/service-app/classes/FanControlLogic.ts

I can see
const MAX_SPEED_JUMP = 2;
const SPEED_JUMP_THRESHOLD = 20;

maybe this '20' could be set to 10 ? I can try a local build, who knows.

**Comment by squalou** [comment]
Manually built / tweaked
```
FanControlLogic.ts
```

added this hardcoded value :
```
        // Adjust for hardware capabilities
        this._fansMinSpeedHWLimit = 10;
```

works fine so far.

**Comment by tuxedoxt** [comment]
Hello,

if I remember correctly, although it's possible that it it many cases works with lower speeds, fans in the devices are rarely spec'ed for use below 20% (rather above). Therefore using these values is in general avoided.

Per device tweaking to find the sweet spot (by the user) could still be an (advanced) setting or similar.

**Comment by tuxedoder** [comment]
Closing due to hardware limitations.
