### ISSUE TITLE
Impossible build

### ISSUE THREAD

**Issue by squalou** [tuxedocomputers/tuxedo-control-center#264]
Hi,

following instructions I get following errors when running npm install

```
npm ERR! gyp info using node@16.19.0 | linux | x64
npm ERR! gyp info find Python using Python version 3.10.6 found at "/usr/bin/python3"
npm ERR! gyp http GET https://atom.io/download/electron/v13.6.9/node-v13.6.9-headers.tar.gz
npm ERR! gyp http 200 https://github.blog/2022-06-08-sunsetting-atom/
npm ERR! gyp WARN install got an error, rolling back install
npm ERR! gyp ERR! configure error 
npm ERR! gyp ERR! stack Error: TAR_BAD_ARCHIVE: Unrecognized archive format

```

Apparently this could com from a dependency relying on atom, which was archived.

Any idea how to solve this ?

**Comment by squalou** [comment]
I managed to download node-v16.19.0-headers.tar.gz

then set things like so :

```
npm config set tarball /tmp/node/node-v16.19.0-headers.tar.gz
```

then npm install --force would run till the end.

With lots of warnings 

But mainly ,nowhere any `tccd` binary to be found, 

Your README could clearly be a bit more explicit, I have no idea what to do now.

**Comment by Kangie** [comment]
+1, can't build from source.

Atom.io was sunsetted in 2022. Please update your build.

**Comment by squalou** [comment]
for the records here's my build instructions

```bash
#!/bin/bash
set -e
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
nvm use 16.19.0 
npm config set tarball /tmp/node-v16.19.0-headers.tar.gz
npm install --force 
npm run build
npm run pack-prod -- deb
```

**Comment by Kangie** [comment]
Seems to work with v2.0.x, this can probably be closed.
