### ISSUE TITLE
TCC not working with Kernel 6.1.7

### ISSUE THREAD

**Issue by nift-d** [tuxedocomputers/tuxedo-control-center#265]
Since the last Kernel-update to 6.1.7 I have no control over the fan speed and tcc can not display the cpu temperature. When I revert back to 6.1.6 it works perfectly.

tcc version: 1.2.4
os: fedora 37 KDE
pc: InfinityBook S14 v5

**Comment by silles79** [comment]
works for me on vanilla 6.1.7.

make sure u have the tuxedo modules compiled:

```
lsmod |grep tuxedo

tuxedo_io              24576  1
tuxedo_keyboard        53248  3 tuxedo_io,uniwill_wmi,clevo_wmi
```

worth checking if u have dkms and it worked to build modules. logs are
/var/lib/dkms/tuxedo-keyboard

**Comment by nift-d** [comment]
`lsmod |grep tuxedo
tuxedo_io              20480  0
tuxedo_keyboard        61440  3 clevo_acpi,tuxedo_io,clevo_wmi
sparse_keymap          16384  2 intel_hid,tuxedo_keyboard`

I dont have a log for 6.1.7.

**Comment by nift-d** [comment]
@silles79 
I reinstalled dkms with no changes. kernel versions beyond 6.1.6 do not work. 

do you have any suggestions?

**Comment by silles79** [comment]
is there anything useful in logs? like
journalctl -xeu tccd

**Comment by nift-d** [comment]
yes, it say:

> Feb 03 11:07:36 ralf tccd[937]: Starting daemon v1.2.4 (node: v14.4.0 arch: x64)
Feb 03 11:07:36 ralf tccd[937]: No tuxedo-io found on start
Feb 03 11:07:36 ralf tccd[937]: Filled missing settings with default: /etc/tcc/settings
Feb 03 11:07:36 ralf tccd[937]: Daemon started
Feb 03 11:07:37 ralf tccd[937]: FanControlWorker: Control unavailable

I searched for tuxedo-io with dnf, but got no results. It is strange since it does not require tuxedo-io with kernel 6.1.6.

**Comment by snizzler** [comment]
We have the same problem under Fedora 37. When you do a reinstall of the TCC `systemctl status tccd `shows that tuxedo-io is functional. After reboot tccd tells you that no tuxedo-io has been found.

**Comment by vmaurin** [comment]
With the copr version, I had an issue where the module were uninstalled just after the setup, see https://copr.fedorainfracloud.org/coprs/kallepm/tuxedo-keyboard/

To solve it :  
* do a dnf remove of control center + tuxedo keyboard
* (eventually reboot)
* do a dnf install of both
Then it should work again

**Comment by nift-d** [comment]
I am using the copr version, but reinstalling did not do the trick. Now I am stuck with the noisy laptop.

![grafik](https://user-images.githubusercontent.com/88383796/218222414-04fe0b88-e142-49db-acc2-c3cf46985c89.png)

**Comment by nift-d** [comment]
ok I tried uninstalling tuxedo-keyboard, tuxedo-control-center and dkms, and installing them again after reboot
```zsh
sudo dnf remove tuxedo-keyboard tuxedo-control-center dkms
```
it did not work

then I noticed that there is no kernel module installed for my current kernel (now 6.1.10 despite the title)
```zsh
ll /var/lib/dkms/tuxedo-keyboard
```

```zsh
drwxr-xr-x. 1 root root 56 18. Jan 14:41 3.1.2
drwxr-xr-x. 1 root root 98 12. Feb 17:37 3.1.3
lrwxrwxrwx. 1 root root 35 23. Dez 12:32 kernel-6.0.13-300.fc37.x86_64-x86_64 -> 3.1.2/6.0.13-300.fc37.x86_64/x86_64
lrwxrwxrwx. 1 root root 34 18. Jan 14:40 kernel-6.1.5-200.fc37.x86_64-x86_64 -> 3.1.3/6.1.5-200.fc37.x86_64/x86_64
```
and:
```zsh
dkms status
```
```zsh
Error! Could not locate dkms.conf file.
File: /var/lib/dkms/tuxedo-keyboard/3.1.2/source/dkms.conf does not exist.
```
this is strange, since the currently installed version of tuxedo-keyboard is 3.1.3

so I decided to install the tuxedo-keyboard module from the github page. resulting in the tcc working again
```zsh
insgesamt 12
drwxr-xr-x. 1 root root 56 18. Jan 14:41 3.1.2
drwxr-xr-x. 1 root root 98 12. Feb 17:37 3.1.3
lrwxrwxrwx. 1 root root 35 23. Dez 12:32 kernel-6.0.13-300.fc37.x86_64-x86_64 -> 3.1.2/6.0.13-300.fc37.x86_64/x86_64
lrwxrwxrwx. 1 root root 35 12. Feb 17:37 kernel-6.1.10-200.fc37.x86_64-x86_64 -> 3.1.3/6.1.10-200.fc37.x86_64/x86_64
lrwxrwxrwx. 1 root root 34 18. Jan 14:40 kernel-6.1.5-200.fc37.x86_64-x86_64 -> 3.1.3/6.1.5-200.fc37.x86_64/x86_64
```
but dkms status still says the dkms.conf for tuxedo-keyboard 3.1.2 is missing.

I dont get that, but the laptop is quiet again. what went wrong here? never did I have to install the kernel module by myself. I expect that I have to repeat that with every kernel update in the future. how is this supposed to work. should the kernel update trigger the installation of a new module? or should tcc detect a new kernel and trigger the installation?
