### ISSUE TITLE
Where are the log files tcc logs to?

### ISSUE THREAD

**Issue by brunoais** [tuxedocomputers/tuxedo-control-center#27]
I'm trying to use bash and cron to automate tcc profile changes.
For some reason, the profile changes are not working. E.g.

`./tccd --new_settings <(tcc_profile_generator.py 'normal' 'normal')`

tcc_profile_generator.py (without the security steps):
```
#! /usr/share/python3
from sys import argv
import json
print(json.dumps({"stateMap":{"power_ac": argv[1],"power_bat": argv[2]}}))
```
This fails with: 

> Error on read option --new_settings with path: /dev/fd/63

How do I find out what's wrong?

I've tried to test it on my machine by compiling and trying to run tccd but I can't find the instructions on how to compile it successfully.

VSC fails with:

> Cannot launch program '/[path/toRepo]/tuxedo-control-center/
src/e-app/main.ts' because corresponding JavaScript cannot be found.

and `node install` doesn't seem to generate a new tccd file.

**Comment by tuxedoxt** [comment]
There are many questions there but to answer the main one..

Logging is for the moment done through stdout. Running tccd from the console will output it in the console. Running through systemd it can be found through journalctl eg. `journalctl -u tccd.service`

**Comment by tuxedoxt** [comment]
> 
> This fails with:
> 
> > Error on read option --new_settings with path: /dev/fd/63
> 
> How do I find out what's wrong?
> 

The error message can be found by a short search through the code and seems to mean that it cannot read the provided file. Could mean that it doesn't exist or doesn't have the rights to read it or fails to parse the json. Yes there could be more info and it seems like the exception message is not included there meaning the propagated message is not shown.

**Comment by brunoais** [comment]
After painstaking search, I found out that there was a null byte in the file with JSON.
That took me quite a while.

**Comment by brunoais** [comment]
Thank you for that help!
