### ISSUE TITLE
Keyboard backlight broken on Aura 15 Gen 1 with TCC 2.0.0

### ISSUE THREAD

**Issue by TiGR** [tuxedocomputers/tuxedo-control-center#277]
So, I've updated TCC. Now keyboard backlight control no longer works. Pressing Fn+ backlight control keys on a numpad produces no result. I can't turn it of, change the brightness or change color using the hotkeys. Moreover, TCC has a page dedicated to keyboard leds, but the only control available there is brightnes, and changing the slider value produces no result. So, backlight is constantly on.

Also, when I press change color hotkey I see messages in the syslog like "tuxedo_keyboard: set_next_color_whole_kb(): new_color_id: 4, new_color_code FFFF00". But nothing actually happens.

Linux 6.1.0-1009-tuxedo, Kubuntu 22.04, KDE Neon, all updates installed.

**Comment by tuxedoxt** [comment]
Hello,

tried a reboot?

**Comment by TiGR** [comment]
Well, reboot helped, thanks
