### ISSUE TITLE
Keyboard backlight is disabled after sleep

### ISSUE THREAD

**Issue by kvirikroma** [tuxedocomputers/tuxedo-control-center#279]
When my laptop (Tuxedo Aura 15 gen 2 with Tuxedo OS) suspends, the keyboard backlight is being disabled, which is normal. However, when it continues, the keyboard lights just blink once and turn off again. The config in the Tuxedo Control Center changes by itself to 0% brightness. Changing it back to higher value fixes it in the particular case, but with next sleep the keyboard will turn black again. Disabling the keyboard backlight control in settings leads to another issue: after the reboot the keyboard will use default backlight color and brightness (0xFFFFFF and 100%), even though the config in /etc/modprobe.d/tuxedo_keyboard.conf says otherwise (it's being ignored for some reason, i guess)
Tuxedo control center version: 2.0.0
Tuxedo keyboard version: 3.2.0
Kernel version: 6.1.0-1009-tuxedo

**Comment by kvirikroma** [comment]
Update: this works only when I close the laptop (not for usual "sudo systemctl suspend"). I guess it's somehow related to plasma's screen disabling: when i set the "When laptop lid closed" to "Turn off screen", the exact same thing happens: the keyboard turns black due to its brightness in TCC set to 0%, even though the laptop did not suspend

**Comment by tuxedoxt** [comment]
Hello,

reproduced on lid close => sleep => lid open => wakeup.

It doesn't happen when using Fn+Sleep key or other means of putting it to sleep so probably related to restoring an already "turned off" value (provoked through lid action).

**Comment by kvirikroma** [comment]
The issue seems to disappear after a few months
