### ISSUE TITLE
TCC profile changer companion program

### ISSUE THREAD

**Issue by brunoais** [tuxedocomputers/tuxedo-control-center#28]
I got somewhat frustrated with how slow it is to get a profile changed, specially when the CPU is constrained and the lack of ability to assign shortcuts to change profiles, so that lead me to make an utility program that accesses directly to the backend and changes the profile in use.
https://github.com/brunoais/tuxedo-control-center-profile-changer/tree/master

I hope it can be useful for other people too.

**Comment by nickma82** [comment]
nice, licenses do not match with tuxedo ones... 
Also a CI artifact creation would be nice... :smile:

**Comment by nickma82** [comment]
P.s. Ticket is ready to be closed.

**Comment by brunoais** [comment]
@nickma82 It's MIT license. It can be used with GPL no problem.
Dunno when makes sense to close this issue, though.

**Comment by nickma82** [comment]
Then I'd either go for a merge or close the ticket..

**Comment by brunoais** [comment]
I can try going for a merge but if so, I think I should clean up the code a little bit.

**Comment by brunoais** [comment]
I still need to clean up the code but I can't run TCC without the fan making me headaches. I'm waiting for a replacement fan.

**Comment by brunoais** [comment]
Not needed anymore
