### ISSUE TITLE
Since TCC 2 keyboard backlight always on after boot and resume

### ISSUE THREAD

**Issue by toastedghost** [tuxedocomputers/tuxedo-control-center#280]
Hi,

since the update to TuxedoControlCenter 2, the keyboard backlight is always active at the minimum level after booting, although disabled in the BIOS and set to 0% in the TCC. After logging in, the backlight in the TCC must first be set to a value greater than 0% and then back to 0% to turn it off again. fn+spacebar still works to select the backlight level or turn it off. The system used is Kubuntu 22.04.02 LTS on Pulse 15 Gen 1

**Comment by toastedghost** [comment]
Today I used the standby mode of my laptop and after I woke it up, the keyboard backlight was on. However, 0% is still set for the keyboard backlight brightness in TCC.

**Comment by toastedghost** [comment]
Maybe this seems to be an issue with https://github.com/tuxedocomputers/tuxedo-keyboard because after disabling keyboard backlight control in TCC the backlight is still enabled after boot.

**Comment by toastedghost** [comment]
Have created a new issue at keyboard module https://github.com/tuxedocomputers/tuxedo-keyboard/issues/179

**Comment by Matombo** [comment]
Can't reproduce it. Given: There is a very recent firmware update that is allready applied to my test device.

What you set in the BIOS menu is ignored by the OS/Tuxedo Control Center. It should set it to the last value on shutdown during boot (design decision to have a predictabel behaviour across all our devices).

Can you help me debug the rest?

Please install the latest BIOS and EC firmware version. And see if that fixes it.
Which version of tuxedo-control-center and tuxedo-keyboard are you running?

**Comment by toastedghost** [comment]
Hi,

the problem is still not solved. The problem is independent of whether the keyboard backlight control is activated in the TCC settings or not. At every boot, the keyboard backlight is switched on again, although it was switched off before the shutdown.

As I found other similar issues at tuxedo-keyboard, I closed this ticket and created a new one there, as it sounded like the problem was more related to tuxedo-keyboard: https://github.com/tuxedocomputers/tuxedo-keyboard/issues/179.

Current BIOS is N.1.07A05, EC is 1.09.30, tuxedo-control-center is version 2.0.5 and tuxedo-keyboard is version 3.2.3.
