### ISSUE TITLE
A JavaScript error occured in the main process

### ISSUE THREAD

**Issue by dzavodnikov** [tuxedocomputers/tuxedo-control-center#282]
**A JavaScript error occured in the main process**
After run by pressing `[Fn]+[F3]` and closing TEXEDO Control Center I got and error message:
```
Uncaught Exception:
TypeError: Cannot read property 'setMenuBarVisible' of null
  at BowserWindow.<anonymous>(/opt/texedo-control-center/
resource/app.asar/dist/texedo-control-center/e-app/main.js:
432:57)
  at BowserWindow.emit (events.js:315:20)
```
[ScreenShot](https://drive.google.com/file/d/1pqs8dcxbwgi5H549H2oowsLdvA7qXrCi/view?usp=sharing)

**Comment by tuxedoxt** [comment]
Hello,

issue was found to trigger pressing the shortcut multiple times while the GUI was loading. This should be fixed as of v2.0.2. Please reopen if issue reappears.
