### ISSUE TITLE
version 2.0.2 ?

### ISSUE THREAD

**Issue by munix9** [tuxedocomputers/tuxedo-control-center#284]
There is currently a 2.0.2 version in https://rpm.tuxedocomputers.com/opensuse/15.4/x86_64/ , but here in the repository there is neither a tag nor a changelog for it.

As far as I can see no new commits have been added since version 2.0.0.

**Comment by Chartman123** [comment]
In version 2.0.2, the program cannot be started, I always get the message that the file /usr/bin/tuxedo-control-center can't be found. When I have a look at the file list in YaST, this file is indeed missing in the package.

**Comment by munix9** [comment]
ok, that's taken care of, thanks.

**Comment by munix9** [comment]
tag for 2.0.2 is still missing.
thx!

**Comment by tuxedoxt** [comment]
Ah right, still missing, there we go.
