### ISSUE TITLE
Reset profile after upgrade to 2.0.2

### ISSUE THREAD

**Issue by peshkopy** [tuxedocomputers/tuxedo-control-center#286]
Hi, I used “Cool and breezy” profile and after upgrade to 2.0.2, the profile is “Tuxedo Defaults”.

On Clevo NH55DCQ + Ubuntu 22.04

**Comment by tuxedoxt** [comment]
Hello,

this is not new to 2.0.2. But "TUXEDO Defaults" is the new default. If missing and for some reason profile mapping failed it will be added (as custom profile) and assigned.

Question is why it felt the need. Just to check, is "cool and breezy" still in the list?

**Comment by peshkopy** [comment]
Hello @tuxedoxt,

Every time I reboot, I lose the profile “Cool and breezy” (or another different from default) for profile  "TUXEDO Defaults".
To avoid this loss, I edited the "TUXEDO Defaults" profile ;-)

**Comment by tuxedoxt** [comment]
Hello,

oh hmm weird, I'll investigate.

**Comment by KillerCodeMonkey** [comment]
dudes... i think i got it... it is not enough to toggle the profile. you need to go to the detail few (dot menu - detail view) and click on "Mains | Battery" for "Activate profile automatically on".

After that it seems to save it as default profile.

**Comment by tuxedoder** [comment]
> it is not enough to toggle the profile. you need to go to the detail few (dot menu - detail view) and click on "Mains | Battery" for "Activate profile automatically on". And then click the save icon.

This is correct. To temporarily set a profile, you can just use that toggle button. If you want to have persistent configs that will apply after reboot, you need to map it to either charging or battery preset. I am closing this issue since it is resolved.
