### ISSUE TITLE
Appindicator icon not showing [Gnome 44]

### ISSUE THREAD

**Issue by yucellmustafa** [tuxedocomputers/tuxedo-control-center#287]
Fedora 38
Gnome 44

![image](https://user-images.githubusercontent.com/49123562/229640092-257c9df8-178b-4a9f-8cd1-71241d28e867.png)

**Comment by tuxedoxt** [comment]
Hello,

is this an install from our rpm package including dependencies?

**Comment by yucellmustafa** [comment]
> Hello,
> 
> is this an install from our rpm package including dependencies?



```bash
sudo dnf config-manager --add-repo https://rpm.tuxedocomputers.com/opensuse/15.4/repo-tuxedo-computers.repo
sudo dnf install tuxedo-control-center -y
```

This is how I'm installing.

**Comment by tuxedoherbert** [comment]
@yucellmustafa is still still open?
