### ISSUE TITLE
Turbo fan enable option

### ISSUE THREAD

**Issue by utrucceh** [tuxedocomputers/tuxedo-control-center#289]
Hi, in windows app there was option to enable turbo fan directly, is there any command or button for this on linux?

**Comment by Kangie** [comment]
`Fn + 1` should enable that for any Clevo/Tuxedo machine. This shortcut is in firmware, doesn't require any control centre running.

**Comment by utrucceh** [comment]
Thanks,
Tuxedo control center working with tongfang laptops but `Fn + 1` shortcut not working :S
Thanks a lot anyway
