### ISSUE TITLE
keyboard backlight settings do no presist after lid is closed 

### ISSUE THREAD

**Issue by osho741** [tuxedocomputers/tuxedo-control-center#291]
If i close the lid on my Pangolin 11 laptop with this application running the keyboard backlight reverts to default settings in app and I have to turn it back on.   This is when running fedora 38

**Comment by Matombo** [comment]
Probably related to a gnome bug: https://gitlab.gnome.org/GNOME/gnome-settings-daemon/-/issues/745

Does it happen on other Desktop environments?

**Comment by tuxedoder** [comment]
If the issue persists in tcc 2.1.7 and tuxedo drivers 4.2.2 and occurs outside of tcc, mention it in the [tuxedo drivers gitlab repository](https://gitlab.com/tuxedocomputers/development/packages/tuxedo-drivers/-/issues). However, if the issue only arises when tcc is visible, I will reopen this issue.
