### ISSUE TITLE
Manual desired battery power level -selection

### ISSUE THREAD

**Issue by lietu** [tuxedocomputers/tuxedo-control-center#293]
It seems currently the Control Center allows only selection of a handful of pre-selected options, 100%, 90%, or 80%. I would personally prefer to keep the battery around 50-60% for maximum longevity. Why not add an option to select any % between 50-100%?

**Comment by tuxedoxt** [comment]
Hello, please see https://github.com/tuxedocomputers/tuxedo-control-center/issues/299#issuecomment-1598304869
