### ISSUE TITLE
since v2.0.5 no symlink: /usr/bin/tuxedo-control-center (RPM for SUSE)

### ISSUE THREAD

**Issue by temirg** [tuxedocomputers/tuxedo-control-center#304]
Hello,

since version 2.0.5 of TCC symbolic link "/usr/bin/tuxedo-control-center" is missing.
Must be created manually.

Repo: https://rpm.tuxedocomputers.com/opensuse/15.4

Regards, temirg.

**Comment by temirg** [comment]
Strange:
Upgrade v2.0.8 to v2.0.9:
If the symlink exists (created manually), it will then be deleted, despite the install log:

```
# 2023-09-27 10:48:20 tuxedo-control-center_2.0.9.rpm installed ok
# Additional rpm output:
# cp: cannot stat '/opt/tuxedo-control-center/resources/dist/tuxedo-control-center/data/dist-data/com.tuxedocomputers.tomte.policy': No such file or directory
# ln: failed to create symbolic link '/usr/bin/tuxedo-control-center': File exists

# 2023-09-27 10:48:20|install|tuxedo-control-center|2.0.9-1|x86_64||tuxedo|a39712b36f6956fb6e16ec6c3a2aca05f53cab4c0dd3e17028385ee42ecd9897|
```

If the symlink is manually deleted beforehand, it will not be created:

```
# 2023-09-28 12:55:28 tuxedo-control-center_2.0.9.rpm installed ok
# Additional rpm output:
# cp: cannot stat '/opt/tuxedo-control-center/resources/dist/tuxedo-control-center/data/dist-data/com.tuxedocomputers.tomte.policy': No such file or directory
# 
2023-09-28 12:55:28|install|tuxedo-control-center|2.0.9-1|x86_64||tuxedo|a39712b36f6956fb6e16ec6c3a2aca05f53cab4c0dd3e17028385ee42ecd9897
```

In both cases - no symlink after installation.
Are the pre-/post-scripplets not running correctly?

@tuxedoxt: do you need additional information?

Regards, temirg.

**Comment by schrapm3** [comment]
Can confirm that on Leap 15.5

**Comment by temirg** [comment]
The same in #354

**Comment by temirg** [comment]
Good news:
At least the update to the latest version 2.1.6 no longer has the problem.
Maybe it was already during the update to version 2.1.5.

@schrapm3: what about the Leap 15.5?

Regards, temirg.

**Comment by temirg** [comment]
Hello,

thank you very much, the issue is gone.
Closing.

Best Regards, temirg.
