### ISSUE TITLE
openSUSE Leap 15.5?

### ISSUE THREAD

**Issue by m-ghaoui** [tuxedocomputers/tuxedo-control-center#305]
openSUSE Leap 15.5 was released a few days ago.

https://rpm.tuxedocomputers.com/opensuse/ does not yet have a 15.5 directory. Any plans to release this?

Thanks!

**Comment by tuxedoxt** [comment]
Hello,

as far as I know this is "in progress".

**Comment by m-ghaoui** [comment]
![image](https://github.com/tuxedocomputers/tuxedo-control-center/assets/481297/44be9e5b-90b9-42e2-a633-9b3774c3ed6c)

Looks like it's done :-)

**Comment by knordsiek** [comment]
SUSE 15.5 is in progress it is not ready to shot it out yet
