### ISSUE TITLE
Fan control unavailable

### ISSUE THREAD

**Issue by Homo-carbonis** [tuxedocomputers/tuxedo-control-center#307]
I'm running Void Linux on my Polaris 15. I have the tuxedo-keyboard dkms module installed (there is a package for it provided in the repos).

```
$ uname -a
Linux polaris 6.1.21_1 #1 SMP PREEMPT_DYNAMIC Fri Mar 24 00:43:29 UTC 2023 x86_64 GNU/Linux

$ dkms status
tuxedo-keyboard/3.2.5, 6.1.21_1, x86_64: installed
```

When I start tccd i get this:
```
$ sudo /opt/tuxedo-control-center/dist/tuxedo-control-center/data/service/tccd --start
Starting daemon v2.0.7 (node: v14.20.0 arch: x64)
tuxedo-io ver 0.3.5 [ interface: inactive ]
Detected no keyboard backlight
Daemon started
FanControlWorker: Control unavailable
```

and none of the controls in the GUI seem to work except the screen backlight.

**Comment by tuxedoxt** [comment]
Hello,

seems like driver is installed but possibly not loaded. lsmod and kernel log might show something.

**Comment by Homo-carbonis** [comment]
It's definitely loaded
```
$ lsmod | grep tux
tuxedo_io              24576  0
tuxedo_keyboard        57344  1 tuxedo_io
led_class_multicolor    16384  1 tuxedo_keyboard
sparse_keymap          16384  2 asus_wmi,tuxedo_keyboard
```
In dmesg I just have
`tuxedo_keyboard: module init`

**Comment by Homo-carbonis** [comment]
Brilliant, it works. Thank you.

**Comment by yurazinko** [comment]
Unfortunatelly fan control now also unavailable on Tuxedo Infinitybook Pro with native Tuxedo OS on it.

**Comment by zoidable** [comment]
Dame here with Gemini 2 on Manjaro. Used to work until a few days ago though, so it seems to be connected to some 3rd party/kernel update...

**Comment by zoidable** [comment]
Apparently the tuxedo-keyboard module wasn't rebuild after updating the kernel. It's working again for me.
