### ISSUE TITLE
[Feature Request] Add option to keep tccd in foreground

### ISSUE THREAD

**Issue by Homo-carbonis** [tuxedocomputers/tuxedo-control-center#308]
For the purposes of writing init services it would be really helpful to have a foreground/no-daemonize option for tccd. Currently runit continuously tries to restart tccd because it appears to have exited.

Using s6-fghack apparently [worked](https://github.com/tuxedocomputers/tuxedo-control-center/issues/65#issuecomment-948568388) with older versions but now doesn't.

**Comment by xtoffer** [comment]
Hello,

if run with `./tccd --start` it should run in the "foreground" and log to stdout. What would be required exactly?

**Comment by Homo-carbonis** [comment]
On closer inspection I may have misunderstood the problem. It seems tccd runs in the foreground when started from an interactive shell but when started by runit it keeps exiting and restarting.
