### ISSUE TITLE
Issue with running TUXEDO Control Center on Arch Linux

### ISSUE THREAD

**Issue by yibajianghudao** [tuxedocomputers/tuxedo-control-center#309]
I am encountering issues while trying to run the TUXEDO Control Center on my Arch Linux system. I have followed the installation instructions provided in the project's README file, but I am unable to launch the application successfully.

Here are the steps I have taken:

Cloned the repository: git clone https://github.com/tuxedocomputers/tuxedo-control-center
Installed the required dependencies: npm install;I have encountered another issue where there is no package available for installing `libudev-dev` mentioned in the README file on Arch Linux. I'm unsure if `libudev-dev` is already installed on my Arch Linux system since I have installed other dependencies successfully during the installation process (so I didn't pay attention to it).
Updated the tccd.service file with the correct paths to the executable.
Reloaded systemd and started the tccd service.
However, when I try to access the Control Center by visiting http://localhost:4711/, I am not able to see anything. Additionally, when I check the status of the tccd service using systemctl status tccd, it shows that the service has failed to start.

I checked the log and it appears as follows:

× tccd.service - TUXEDO Control Center Service
     Loaded: loaded (/etc/systemd/system/tccd.service; disabled; preset: disabled)
     Active: failed (Result: exit-code) since Tue 2023-07-04 19:12:29 CST; 6s ago
   Duration: 544us
    Process: 39997 ExecStart=/home/JiangHuDao/tuxedo-control-center/resources/dist/tuxedo-control-center/data/service/tccd --start (code=exited, status=203/EXEC)
   Main PID: 39997 (code=exited, status=203/EXEC)
        CPU: 407us

7月 04 19:12:29 JiangHuDaoArch (tccd)[39997]: tccd.service: Failed at step EXEC spawning /home/JiangHuDao/tuxedo-control-center/resources/dist/tuxedo-control-center/data/service/tccd: No such file or directory
7月 04 19:12:29 JiangHuDaoArch systemd[1]: Started TUXEDO Control Center Service.
7月 04 19:12:29 JiangHuDaoArch systemd[1]: tccd.service: Main process exited, code=exited, status=203/EXEC
7月 04 19:12:29 JiangHuDaoArch systemd[1]: tccd.service: Failed with result 'exit-code'.

I understand that there is an issue with the path. So, I checked the files I cloned and found that the `tuxedo-control-center/data/service/tccd` path mentioned in the README.md file is not present. I tried searching for the `tccd` file and found that I only have the `tccd.service` file. I assumed that this is the file the path should point to, so I changed the path to `/home/JiangHuDao/tuxedo-control-center/src/dist-data/tccd`. However, I encountered a new error: `tccd.service: Failed at step EXEC spawning /home/JiangHuDao/tuxedo-control-center/src/dist-data/tccd: No such file or directory`. 

Then I added the file extension to the path:
`/home/JiangHuDao/tuxedo-control-center/src/dist-data/tccd.service`

But after running it again, I received the following error:
7月 04 19:18:04 JiangHuDaoArch (.service)[40235]: tccd.service: Failed to locate executable /home/JiangHuDao/tuxedo-control-center/src/di>
7月 04 19:18:04 JiangHuDaoArch (.service)[40235]: tccd.service: Failed at step EXEC spawning /home/JiangHuDao/tuxedo-control-center/src/d>
7月 04 19:18:04 JiangHuDaoArch systemd[1]: Started TUXEDO Control Center Service.
7月 04 19:18:04 JiangHuDaoArch systemd[1]: tccd.service: Main process exited, code=exited, status=203/EXEC
7月 04 19:18:04 JiangHuDaoArch systemd[1]: tccd.service: Failed with result 'exit-code'.

It seems that the path I found is not the correct file path that should be provided.

Could you please assist me in resolving this problem? Any guidance or suggestions would be greatly appreciated.

Thank you!

**Comment by tuxedoxt** [comment]
Hello,

sounds like you need to build it first.

```
npm run build
```

**Comment by yibajianghudao** [comment]
I have successfully solved this problem, the software exists in arch's aur repository.
Thanks
