### ISSUE TITLE
TCC questions

### ISSUE THREAD

**Issue by leinardi** [tuxedocomputers/tuxedo-control-center#311]
I have some questions about the Tuxedo Control Center:

1. I would like to completely reset all the profiles store on my system with the default ones, what's the best way to do that?
2. How can I verify if my current profile is using the main or the battery power profile? I just want to verify that, when I use my Dell WD-19 docking station with Power Delivery, the main power profile is used, since I want to have the maximum performances. What's the best way to check that?

**Comment by tuxedoxt** [comment]
Hello,

1. I guess there is not a convenient way to do this. You could uninstall and reinstall. Or remove `/etc/tcc/profiles` (and possibly `/etc/tcc/settings` for profile assignments etc) and `systemctl restart tccd`. This should recreate configs with default values for your device.
2. On the dashboard the currently active profile is shown by name. That means you can plug in the dock and check that dashboard shows the profile name of choice. Further in the profile overview list (boxes) the currently active one has a green dot. The profiles chosen for battery and mains use will have a battery and mains plug icon respectively.

**Comment by leinardi** [comment]
> 1. I guess there is not a convenient way to do this. You could uninstall and reinstall. Or remove `/etc/tcc/profiles` (and possibly `/etc/tcc/settings` for profile assignments etc) and `systemctl restart tccd`. This should recreate configs with default values for your device.

Thanks, uninstalling and reinstalling worked! I didn't try because I assumed the profiles were persisted somewhere in userspace, but uninstalling it wiped the `/etc/tcc/` directory so that fixed it.

I have one more question: to squeeze the maximum performance out of the CPU not caring about power efficiency should I do something else beside checking `Maximum performance` inside the profile and selecting an appropriate cooling profile? I see that the performance core boosts around 2.8 - 2.9 GHz with the package temperature around 60°C. Is it possible to get higher frequencies allowing the CPU to reach 70° or 80°?

**Comment by tuxedoxt** [comment]
> > 1. I guess there is not a convenient way to do this. You could uninstall and reinstall. Or remove `/etc/tcc/profiles` (and possibly `/etc/tcc/settings` for profile assignments etc) and `systemctl restart tccd`. This should recreate configs with default values for your device.
> 
> Thanks, uninstalling and reinstalling worked! I didn't try because I assumed the profiles were persisted somewhere in userspace, but uninstalling it wiped the `/etc/tcc/` directory so that fixed it.
> 
> I have one more question: to squeeze the maximum performance out of the CPU not caring about power efficiency should I do something else beside checking `Maximum performance` inside the profile and selecting an appropriate cooling profile? I see that the performance core boosts around 2.8 - 2.9 GHz with the package temperature around 60°C. Is it possible to get higher frequencies allowing the CPU to reach 70° or 80°?

The default profile is set without limits. To give more temperature headroom you could choose a fan profile with higher thresholds. As you say you can also check maximum performance which selects the `performance` governor where available. This is more of a "readiness to clock up" hint to the CPU though.
