### ISSUE TITLE
Which nodejs version should I use to build?

### ISSUE THREAD

**Issue by misterhsp** [tuxedocomputers/tuxedo-control-center#313]
Which nodejs version should I use to build? The changelog still says node 14, but it is no longer supported. With nodejs 14 the build does not work anymore.

Thenks...

**Comment by tuxedoxt** [comment]
Hello,

v14 is still used to build and should work. Upgrading is.. on the way :)

**Comment by misterhsp** [comment]
Is TCC still using nodejs 14? Or does the build work with v16 or v18?

Thanks...
