### ISSUE TITLE
Profile change with command line?

### ISSUE THREAD

**Issue by leuchtrakete666** [tuxedocomputers/tuxedo-control-center#318]
Is there a command i didn't  found yet to change profiles with the command line? I use different profiles for different use cases. As it should be. It would be really cool if i could automate the profile switching with scripts.

**Comment by fischerling** [comment]
I stumbled upon https://github.com/brunoais/tuxedo-control-center-profile-changer.

Although, I have not used it or have any other experience with it, I thought I let you know.
