### ISSUE TITLE
CPU frequency settings have no effect, Kernel 6.5.3, opensuse tumbleweed

### ISSUE THREAD

**Issue by svewap** [tuxedocomputers/tuxedo-control-center#319]
no matter which setting I set in the tuxedo-controlcenter regarding CPU clock frequency, the CPUs always clock themselves.
`cpupower frequency-info` says:
```
CPU 13 wird analysiert:
  driver: amd-pstate-epp
  CPUs, die mit der gleichen Hardwarefrequenz laufen: 13
  CPUs, die ihre Frequenz mit Software koordinieren müssen: 13
  Maximale Dauer eines Taktfrequenzwechsels:  Cannot determine or is not supported.
  Hardwarebegrenzungen: 400 MHz - 4.37 GHz
  verfügbare cpufreq-Regler: performance powersave
  momentane Richtlinie: Frequenz sollte innerhalb 400 MHz und 1000 MHz.
                    sein. Der Regler "powersave" kann frei entscheiden,
                    welche Geschwindigkeit er in diesem Bereich verwendet.
  current CPU frequency: Unable to call hardware
  current CPU frequency: 3.57 GHz (asserted by call to kernel)
  boost state support:
    Unterstützt: ja
    Aktiv: ja
    Gesamtzustände: 3
    Pstate-P0:  1800MHz
    Pstate-P1:  1700MHz
    Pstate-P2:  1400MHz
```
Is this a bug deeper in control programs?

**Comment by bziemons** [comment]
Hi, I had the same issue. I solved it by setting the default pstate mode to guided (e.g. build a kernel with the correct default or add `amd_pstate=guided` to kernel cmdline). See https://www.kernel.org/doc/html/latest/admin-guide/pm/amd-pstate.html
This will enable all the other available cpufreq governors as well (like ondemand).

**Comment by crissi-tuxedo** [comment]
Hi svewap,

since this has been a while and alot of updates happened in the meantime, does your problem still persist?

best regards, Crissi

**Comment by svewap** [comment]
Hi, I think we can close this. I'm using the newest kernel in tumbleweed and at this moment I don't have any problems.

**Comment by crissi-tuxedo** [comment]
Hi svewap,

thanks for letting me know!

If you experience any more issues feel free to open a new ticket.

But I of course hope you won't ;)

best regards,
Crissi
