### ISSUE TITLE
Enhancement request: Daemon startup option

### ISSUE THREAD

**Issue by evertvorster** [tuxedocomputers/tuxedo-control-center#320]
Tuxedo control center always displays all the settings when started. 

When autostarting the control center on system startup, having to close this window every time is a little annoying. 

Is there a way of starting the control center so that it goes directly to the panel and starts doing its monitoring thing but does not pop up a window with all the settings? If not, then it would be a nice thing to have.

**Comment by tuxedoxt** [comment]
> Tuxedo control center always displays all the settings when started.
> 
> When autostarting the control center on system startup, having to close this window every time is a little annoying.
> 
> Is there a way of starting the control center so that it goes directly to the panel and starts doing its monitoring thing but does not pop up a window with all the settings? If not, then it would be a nice thing to have.

Hello,

this does not sound like normal behaviour. The autostart option creates a desktop shortcut with the `--tray` option and should therefore not display a window but only create the tray icon/menu on autostart.

**Comment by evertvorster** [comment]
Hi there!

Thanks for the quick response. 
Once I ticked the "Tray start" box in Tuxedo manager, it starts correctly in the tray. 
Closing this ticket.
