### ISSUE TITLE
Not able to connect Oasis `Error: writeBuffer(): not connected`

### ISSUE THREAD

**Issue by qb-0** [tuxedocomputers/tuxedo-control-center#328]
I know that TCC was not written for the Oasis. However, I am still interested in whether the error message could be related to something else, as the Oasis is being displayed to me, and I am sporadically able to connect to and control the Oasis. Are there any additional logs I could check? Perhaps a firmware upgrade/downgrade for the Oasis?

Windows drives me crazy!

```
qb@home ~> tuxedo-control-center
/bin/sh: 1: prime-select: not found
/bin/sh: 1: prime-supported: not found
updateDeviceState error => Error: writeBuffer(): not connected
updateDeviceState error => Error: writeBuffer(): not connected
updateDeviceState error => Error: writeBuffer(): not connected
updateDeviceState error => Error: writeBuffer(): not connected
```

![Bildschirmfoto vom 2023-11-03 22-36-06](https://github.com/tuxedocomputers/tuxedo-control-center/assets/34208612/1030c60d-80aa-4678-951d-8be5eed95b72)
![Bildschirmfoto vom 2023-11-03 21-47-24](https://github.com/tuxedocomputers/tuxedo-control-center/assets/34208612/e8b16aa8-05f4-486a-ac86-90cdbbb54eda)

**Comment by tuxedoherbert** [comment]
Should be fixed with later releases. Please check and reopen if it still appears, thank you :)
