### ISSUE TITLE
Fn+1 Full fan speed

### ISSUE THREAD

**Issue by Vitamin-X** [tuxedocomputers/tuxedo-control-center#331]
When using the windows software Fn+1 is full power, its also configured like that in my EC so when pushing it, the fan goes full speed for a split second until the software reduces the fan speed again.

Is it a bug or wasn't it planed?
do the tuxedo notebooks act differently? cuz i ordered mine from Clevo directly.

**Comment by Vitamin-X** [comment]
is it really completed?

**Comment by tuxedoherbert** [comment]
sorry, closed accidently.

yes, on some devices Fn+F1 triggers full-fan by EC. In windows we let this active because of possible side effects with other tools. In linux we deactivated this unexpected behavior completely.

**Comment by Vitamin-X** [comment]
so no plan on adding it?

**Comment by tuxedoherbert** [comment]
It is already there but we removed it with tuxedo-drivers. You can set full fan at the TCC.
