### ISSUE TITLE
Battery not charging full

### ISSUE THREAD

**Issue by silles79** [tuxedocomputers/tuxedo-control-center#332]
I used to have

   battery
    present:             yes
    rechargeable:        yes
    state:               fully-charged
    warning-level:       none
    energy:              82.044 Wh
    energy-empty:        0 Wh
    energy-full:         82.044 Wh
    energy-full-design:  82.044 Wh
    energy-rate:         3.68424 W
    **voltage:             17.616 V**
    charge-cycles:       N/A
    percentage:          100%
    **capacity:            100%**
    technology:          lithium-ion
    icon-name:          'battery-full-charged-symbolic'

Note voltage 17.6 when full.

Nowdays:
    present:             yes
    rechargeable:        yes
    state:               fully-charged
    warning-level:       none
    energy:              65.016 Wh
    energy-empty:        0 Wh
    energy-full:         65.016 Wh
    energy-full-design:  82.044 Wh
    energy-rate:         0 W
    **voltage:             17.123 V**
    charge-cycles:       N/A
    percentage:          100%
    **capacity:            79.2453%**
    technology:          lithium-ion
    icon-name:          'battery-full-charged-symbolic'

I have fully discharaged battery and selected "Full" in profile.
But still looks like only charging to 80%?

Hardware:
Product: TUXEDO InfinityBook Pro 16 Mk2 - Gen7
Software: Ubuntu 23.10. 
Linux tuxedo 6.5.0-13-generic #13-Ubuntu SMP PREEMPT_DYNAMIC Fri Nov  3 12:16:05 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
Control Center:	2.0.11

Expected: when full profile selected, it should charge to 17.6 and capacity back to ~100%

**Comment by crissi-tuxedo** [comment]
Hi silles,

since this has been a while, does your problem still persist?

best regards, Crissi
