### ISSUE TITLE
Silly nvidia powerstate logic

### ISSUE THREAD

**Issue by right-0903** [tuxedocomputers/tuxedo-control-center#341]
Under X11, open tcc will wake up nvidia, then powerstate become D0, with tcc capture it, tcc will call nvidia-smi, then nvidia keep D0. 
All my electron apps will wake nvidia when starting under X11, I don't know if there is a workaround. Thanks.

This works well with Wayland, but powerstate checking is too frequent, especially when I open console log.

Another off topic, prime worker use `prime-select` or `prime-supported` to check prime status is inappropriate, only Ubuntu provide those things.

**Comment by tuxedoherbert** [comment]
keep the discussion at https://github.com/tuxedocomputers/tuxedo-control-center/issues/360
