### ISSUE TITLE
What would it take to fully support other linux distributions

### ISSUE THREAD

**Issue by kron4eg** [tuxedocomputers/tuxedo-control-center#343]
So I'm running a Fedora and installed TCC from https://copr.fedorainfracloud.org/coprs/kallepm/tuxedo-control-center/ and its partially works (like changing power profiles and fan speeds).

But anything related to GPU is omitted from the UI as some binaries are not found. Is it possible to have some kind of doc/wiki/guide that would provide a list of requirements to the OS (other then tuxedOS), to make TCC fully functional.

**Comment by edwardando** [comment]
Did you fix this?

**Comment by kron4eg** [comment]
No, I didn't fixed anything, this issue is a question.

**Comment by aleeraser** [comment]
Using Fedora as well, I'd be more than interested into this.

**Comment by tuxedoherbert** [comment]
We already support fedora, just add our repo:
https://rpm.tuxedocomputers.com/fedora/

**Comment by aleeraser** [comment]
Thanks.

It looks like `tuxedo-control-center_2.1.4.rpm` has a wrong checksum:

`[MIRROR] tuxedo-control-center_2.1.4.rpm: Downloading successful, but checksum doesn't match. Calculated: 1ffe14e3ba7670a8124de6a3521c292a78778caf201ab5646de078dc9ed77365(sha256)  Expected: dcf7fc9c8ed3acc0a59f419e77cfc45755c4317579b8dc98b4d37dd740d67afc(sha256)`

**Comment by tuxedoherbert** [comment]
Maybe you compare the checksum from the latest version 2.1.6 against the 2.1.4 rpm? Please install the 2.1.6, not the older one :)

**Comment by aleeraser** [comment]
It looks like everything is working correctly though. Also Aquaris connection looks fine!

**Comment by kron4eg** [comment]
> Also, this failure pops up at the end of the installation log:
> 
> `cp: cannot stat '/opt/tuxedo-control-center/resources/dist/tuxedo-control-center/data/dist-data/com.tuxedocomputers.tomte.policy': No such file or directory`

AFAIK, tomte is only available at the debian based systems.

**Comment by aleeraser** [comment]
That's my understanding as well, but I just wanted to point it out.

**Comment by tuxedoherbert** [comment]
Just for the records: https://www.tuxedocomputers.com/en/Infos/Help-and-Support/Instructions/Add-TUXEDO-Computers-software-package-sources.tuxedo#:~:text=Fedora%20and%20derivatives

**Comment by tuxedoder** [comment]
> AFAIK, tomte is only available at the debian based systems.

Tomte currently supports specific versions of Tuxedo OS, Ubuntu, elementary OS, KDE neon and Linux mint.
