### ISSUE TITLE
opens use pre-built package lack dependent to pkexec package.

### ISSUE THREAD

**Issue by please-enter-a-username** [tuxedocomputers/tuxedo-control-center#345]
Hi, sorry for bad English grammar.
Title basically says all.

This makes you can't save any profile change because no password promote window pops up, and that's because pkexec is not installed by default (not only by opensuse 15.5 but also by tcc package).

Manually install pkexec with zypper fixes that.

Additional info:
OS: opens use 15.5 fresh KDE install.
Tcc version: 2.1.2-1 x86_64

**Comment by crissi-tuxedo** [comment]
Hi,

thanks for bringing this to our attention. 
We will talk about this internally and fix the dependencies for TCC.

best regards, Crissi
