### ISSUE TITLE
Missing symlink after update

### ISSUE THREAD

**Issue by MarcoDePollo** [tuxedocomputers/tuxedo-control-center#354]
As usual, after every upgrade, the symlink to /usr/bin/tuxedo-control-center has disappeared, even after the installer claims to not have touched. As stated in another issue, if the symlink is created manually, it will get deleted. If the symlink is not present, it won't be created.

Could you look into fixing this, please?

Opensuse Tumbleweed.

**Comment by temirg** [comment]
[since v2.0.5 no symlink: /usr/bin/tuxedo-control-center (RPM for SUSE) #304 ](https://github.com/tuxedocomputers/tuxedo-control-center/issues/304)

**Comment by temirg** [comment]
#304

**Comment by temirg** [comment]
@MarcoDePollo : does the problem still exist for you?
For me it vanished into thin air.

Regards, temirg.

**Comment by MarcoDePollo** [comment]
@temirg I hadn't noticed that TCC had been updated, this was quietly fixed in v2.1.6

`RPM package upgrade ending up without executable link in /usr/bin`

**Comment by tuxedoxt** [comment]
Hello,

yes as of 2.1.6 it should be fixed. More or less quietly :) 

> RPM package upgrade ending up without executable link in /usr/bin

That's it.

Here's the other issue for reference: https://github.com/tuxedocomputers/tuxedo-control-center/issues/304
