### ISSUE TITLE
Webcam access error

### ISSUE THREAD

**Issue by vallode** [tuxedocomputers/tuxedo-control-center#358]
Machine: Pulse 15 Gen 3
OS: Arch
Tuxedo control center version: 2.1.5

When accessing webcam settings I sometimes receive an "access error" that cannot be closed and re-opens itself a few times a second until the entire UI is inaccessible.

![Screenshot_20240205_102252](https://github.com/tuxedocomputers/tuxedo-control-center/assets/18506096/82d90a8c-feb3-4d9c-8553-e5fa7e0231c4)

This error will keep opening and there is no way of closing it without closing the control center entirely.

**Comment by tuxedoherbert** [comment]
If the Webcam is taken by another application, the TCC can't get control of it. Please check if there is something else running.

**Comment by vallode** [comment]
Looks like it is resolved with the update, thank you!
