### ISSUE TITLE
Add CPU TDP settings in profiles

### ISSUE THREAD

**Issue by effeffe** [tuxedocomputers/tuxedo-control-center#361]
Dear developers,
Can you please add a way to set TDP values by ACPI calls?

For instance, the XMG core 15 IE21 (Polaris Gen 2 (?)) uses the followings for PL1-PL4:
`\_SB.PCI0.LPCB.EC0_.PL1L` -> read stored values
`\_SB.INOU.T1WR` -> write values to EC: 0x81 is PL1, 0x82 is PL2 and 0x84 is PL4,. These values are followed by the hex value in watts, e.g.
`# echo "\_SB.INOU.T1WR 0x85 0xa5"> /proc/acpi/call && cat /proc/acpi/call & printf '\n'`
to write 165W onto PL4.

Thank you

**Comment by tuxedoherbert** [comment]
It's already within the TCC for most of the Tuxedo Books: https://www.tuxedocomputers.com/en/TUXEDO-Control-Center-TCC.tuxedo

**Comment by effeffe** [comment]
> It's already within the TCC for most of the Tuxedo Books: https://www.tuxedocomputers.com/en/TUXEDO-Control-Center-TCC.tuxedo

Can we add support for xmg? Or should I make a pull request for that?
It's a real shame it's not there for xmg laptops too...
