### ISSUE TITLE
please refresh suse repos - the zypper doesn't find currently the TCC 2.1.8

### ISSUE THREAD

**Issue by temirg** [tuxedocomputers/tuxedo-control-center#379]
Hello,

repo files/structure seems to be old, not refreshed with newest packages.
Please refresh suse repos for TCC.

Many thanks.

Regards, temirg.

**Comment by temirg** [comment]
Repo I'm concerned about:
https://rpm.tuxedocomputers.com/opensuse/15.5/repodata/

**Comment by vinzv** [comment]
Thanks for pointing out, this should be fixed now.

**Comment by temirg** [comment]
Thanks, it works now!
