### ISSUE TITLE
Ubuntu 22.04 update fails because of tuxedo-control-center_2.1.10-1_amd64.deb

### ISSUE THREAD

**Issue by viceldan** [tuxedocomputers/tuxedo-control-center#393]
Hi *,
this is the relevant output of:

`apt-get update && apt-get -y dist-upgrade'

You'll find the whole output within the update.log file I provided.

`Die folgenden Pakete werden aktualisiert (Upgrade):
  tuxedo-control-center
... snip ...
Vorbereitung zum Entpacken von .../tuxedo-control-center_2.1.10-1_amd64.deb ...
Entpacken von tuxedo-control-center (2.1.10-1) über (2.1.8) ...
dpkg: Fehler beim Bearbeiten des Archivs /var/cache/apt/archives/tuxedo-control-center_2.1.10-1_amd64.deb (--unpack):
 Fehler beim Anlegen des harten Links »./opt/tuxedo-control-center/resources/dist/tuxedo-control-center/data/dist-data/tuxedo-control-center_256.svg«: Ungültiger Link über Gerätegrenzen hinweg
dpkg-deb: Fehler: »einfügen«-Unterprozess wurde durch Signal (Datenübergabe unterbrochen (broken pipe)) getötet
mv: Aufruf von stat für '/opt/tuxedo-control-center/resources/dist/tuxedo-control-center/data/dist-data/99-webcam.rules' nicht möglich: Datei oder Verzeichnis nicht gefunden
Fehler traten auf beim Bearbeiten von:
 /var/cache/apt/archives/tuxedo-control-center_2.1.10-1_amd64.deb
E: Sub-process /usr/bin/dpkg returned an error code (1)`

Could  you please help me on that?

Thank you and kind regards,

viceldan

**Comment by tuxedoxt** [comment]
Hello, please see https://github.com/tuxedocomputers/tuxedo-control-center/issues/391#issuecomment-2160867329
