### ISSUE TITLE
What happened to the installation documentation?

### ISSUE THREAD

**Issue by m-ghaoui** [tuxedocomputers/tuxedo-control-center#395]
Hi,

I have a Clevo laptop and I usually go to the link in the README to get the installation instructions for Fedora/Ubuntu/OpenSUSE:

> There are pre-build packages for Ubuntu 16.04/18.04/20.04 as well as openSUSE Leap 15.x and Tumbleweed available at our repositories. For details please have a look [over here](https://www.tuxedocomputers.com/en/Infos/Help-and-Support/Instructions/Add-TUXEDO-Computers-software-package-sources.tuxedo#).

The link goes to https://www.tuxedocomputers.com/en/Infos/Help-and-Support/Instructions/Add-TUXEDO-Computers-software-package-sources.tuxedo# but now it seems to be replaced by a product page.

Is the page still available? I don't know the addresses of the repositories.

**Comment by m-ghaoui** [comment]
Here is the Wayback Machine link for 29th of November 2023:

https://web.archive.org/web/20231129193939/https://www.tuxedocomputers.com/en/Infos/Help-and-Support/Instructions/Add-TUXEDO-Computers-software-package-sources.tuxedo

**Comment by tuxedoxt** [comment]
Hmm link might have changed. Here's one that works.

https://www.tuxedocomputers.com/en/Add-TUXEDO-software-package-sources.tuxedo
