### ISSUE TITLE
Keyboard light support

### ISSUE THREAD

**Issue by PhrozenByte** [tuxedocomputers/tuxedo-control-center#4]
First of all: Great work! :+1:

I own a InfinityBook 14 Pro v4 and was wondering whether we can get support for configuring the keyboard illumination. There's a tool for Windows, however, nothing for Linux as far as I know. The keyboard light resets to it's basic profile all the time (i.e. lowest illumination) and I'd really love to make my preferred config persistent.

**Comment by Croydon** [comment]
Agreed. I would also love to have the option to disable the keyboard light completely.

I don't need it and it drains the battery.

**Comment by vinzv** [comment]
Thanks for the kind words all!
We have quite a few things on our roadmap. So expect your wishes to be considered if not even planned to fulfilled. 😉

Meanwhile I'll close this issue. If you have any further requests or ideas feel free to open further ones.

**Comment by Croydon** [comment]
Is the roadmap public?

**Comment by vinzv** [comment]
No, not _yet_. But we're already looking into polishing it a bit to release it into the wild. 😉

**Comment by augustoicaro** [comment]
Any news about it?

What about adding some features from [STE](https://github.com/salihmarangoz/system_tray_extensions)?
This one works well on my MAG-15.

**Comment by MrHappy** [comment]
I noticed this functionality being available on the Windows-tool, but not yet on Linux.
Any timeline when this will become available on Linux (Arch in my case)?
