### ISSUE TITLE
Breaking machines that are dist upgraded on ubuntu

### ISSUE THREAD

**Issue by silles79** [tuxedocomputers/tuxedo-control-center#401]
Upgrade ubuntu to 24.04 and initrams was broken, turns out to be 

 apt-cache policy initramfs-tools
initramfs-tools:
  Installed: 2:0.140ubuntu13.4-tux1
  Candidate: 2:0.140ubuntu13.4-tux1
  Version table:
 *** 2:0.140ubuntu13.4-tux1 100
        100 /var/lib/dpkg/status

which seems to be comming from tuxedo repo and very old version.
More info here:

https://bugs.launchpad.net/ubuntu/+source/linux-firmware/+bug/2067374

![image](https://github.com/tuxedocomputers/tuxedo-control-center/assets/1422674/1c90097a-81b9-43cb-b74f-cb25f707af5b)

**Comment by vinzv** [comment]
This should be fixed by now, just upgrade your system.

Thanks for pointing out!

**Comment by silles79** [comment]
My system was updated. 

I had to manually purge and install official packages 
Maybe just got unlucky and upgraded at the wrong time :shrug:

**Comment by vinzv** [comment]
No, you weren't. We just fixed that problem after you reported it.

So, thanks again for doing so!

**Comment by silles79** [comment]
ok I see. also on top of that distupgrade disabled your repos. so even when I was trying to update it wasn't doing anything

**Comment by vinzv** [comment]
That is a normal Ubuntu behavior and we document that for upgrades we have tested and approved, like 20.04 to 22.04: https://www.tuxedocomputers.com/en/Infos/Help-Support/Instructions/Upgrade-to-Ubuntu-22-04-LTS-and-TUXEDO-OS.tuxedo

24.04 is not ready from our side and even Ubuntu itself does not offer upgrades the regular way until 24.04.1 is released.

**Comment by juergh** [comment]
Disclaimer: I work for Canonical but I'm just a kernel person (no sales ;-) who ended up looking at @silles79's issue.
@vinzv How about engaging with Canonical and making Tuxedo a certified platform? https://ubuntu.com/certified

**Comment by silles79** [comment]
it's still trying to install tuxedos version of initramfs:

sudo apt-get upgrade --simulate 
...
The following packages will be upgraded:
  initramfs-tools initramfs-tools-bin initramfs-tools-core
3 to upgrade, 0 to newly install, 0 to remove and 7 not to upgrade.
Inst initramfs-tools [0.142ubuntu25.1] (2:0.142ubuntu26-tux1 TUXEDO Computers:tuxedo [all]) []
Inst initramfs-tools-core [0.142ubuntu25.1] (2:0.142ubuntu26-tux1 TUXEDO Computers:tuxedo [all]) []
Inst initramfs-tools-bin [0.142ubuntu25.1] (2:0.142ubuntu26-tux1 TUXEDO Computers:tuxedo [amd64])
Conf initramfs-tools (2:0.142ubuntu26-tux1 TUXEDO Computers:tuxedo [all])
Conf initramfs-tools-core (2:0.142ubuntu26-tux1 TUXEDO Computers:tuxedo [all])
Conf initramfs-tools-bin (2:0.142ubuntu26-tux1 TUXEDO Computers:tuxedo [amd64])

not sure why that is necessary

**Comment by vinzv** [comment]
This looks right to me. We updated the version of initramfs-tools for noble and this is the update you are receiving. Or am I missing something?

**Comment by Vitamin-X** [comment]
interesting the upgrade here bricked the whole kernel,  are they maybe related?

https://github.com/tuxedocomputers/tuxedo-control-center/issues/402
