### ISSUE TITLE
cannot see fan speed in xesnsors, linux mint 21.3

### ISSUE THREAD

**Issue by imtiazShakil** [tuxedocomputers/tuxedo-control-center#404]
Hi,

I bought a new TUXEDO Gemini 15 - Gen2 one month ago. I installed Linux Mint 21.3 Cinnamon and installed tuxedo control center and everything is working great so far alhamdulillah.

The problem is I can see CPU fan % in tuxedo control center but cannot find cpu fan information in [xsensors app](https://community.linuxmint.com/software/view/xsensors).

I tried detecting sensors by running  `sudo sensors-detect`.   Below is the message exercept I received
```
Now follows a summary of the probes I have just done.
Just press ENTER to continue: 

Driver `coretemp':
  * Chip `Intel digital thermal sensor' (confidence: 9)

To load everything that is needed, add this to /etc/modules:
#----cut here----
# Chip drivers
coretemp
#----cut here----
If you have some drivers built into your kernel, the list above will
contain too many modules. Skip the appropriate ones!

Do you want to add these lines automatically to /etc/modules? (yes/NO)no

```

I'm not sure if I should add this line as it suggests. 

What can I do to get fan speed info in xsensors app? Thanks

**Comment by tuxedoder** [comment]
This is more related to [`tuxedo-drivers`](https://gitlab.com/tuxedocomputers/development/packages/tuxedo-drivers) than this repository. We are not sure how `xsensor` gathers data, but `tuxedo-drivers` most likely does not provide a standardized userspace interface and thus other applications won't be able to see the values.
