### ISSUE TITLE
Tuxedo Control Center tray icon and tccd.service

### ISSUE THREAD

**Issue by geekthought** [tuxedocomputers/tuxedo-control-center#413]
Hi, 

i really like the icon to be monochrome but cant find where to change the tray icon. Guess its embedded in the binary somewhere. Can I hide the icon or do i even need the control center to be started for profiles to get active? Lets say i changed the battery profile to stationary. Do i need to start the control center or does tccd.service does all this in the background?

**Comment by tuxedoder** [comment]
The icon is within the electron application and can't easily be changed. You would have to rebuild the application with a custom icon.
```typescript
export const tray: TccTray = new TccTray(path.join(__dirname, '../../../data/dist-data/tuxedo-control-center_256.png'));
```
Once you configured with `tcc` you can close it, `tccd` applies the settings. It is not required to have `tcc` open.
