### ISSUE TITLE
Sirius 16 max cpu 900MHz when used with Docking Station

### ISSUE THREAD

**Issue by frickler24** [tuxedocomputers/tuxedo-control-center#414]
Sirius 16 with TuxedoOS 3 and TCC 2.1.13:

I keep having problems with the CPU clock settings of my Sirius 16:
Again and again the clock frequency goes down massively (today sometimes to 900MHz, sometimes also to 544 or 400MHz) with all cores.
The effect is particularly frequent when the notebook is connected to the docking station and is supplied with power via it. Even when the battery is fully charged, it only sporadically goes to 5GHz with a single core. 

If I now load the cores with parallel dd statements, for example, they all go to 900MHz and remain there.
If I unplug the USB-C cable from the docking station, the cores all go to 4.4GHz. I would have expected that to be higher, but at least I have more than a 486 PC...
Repeatedly connecting and disconnecting the USB also leads to high performance when connected to the mains. 
All in all, completely unsatisfactory.

Any help?

**Comment by tuxedoxt** [comment]
Hello,

at a glance it does not look relevant to this project. Unless it only happens in combination with certain TCC settings. Please correct me if I'm wrong.

It does sound like weird behaviour however. Please contact support to properly track it.

https://www.tuxedocomputers.com/en/Contact.tuxedo
