### ISSUE TITLE
issue on installing

### ISSUE THREAD

**Issue by mertanild** [tuxedocomputers/tuxedo-control-center#42]
I'm new on Linux so I think I couldn't understand this step:
 2. Edit the `tccd.service` (exec start/stop) to point to `<dev path>/dist/tuxedo-control-center/data/service/tccd`.
The problem is I don't know what to write to "dev path". 
I'll be very happy if you help me.

**Comment by mbway** [comment]
if you just want to install and use tuxedo control center then it would be better if you used the [pre-built packages](https://www.tuxedocomputers.com/en/Infos/Help-and-Support/Instructions/Add-TUXEDO-Computers-software-package-sources.tuxedo#).

When building the control center on your machine, the 'dev path' refers to the directory where you cloned the git repository to. So if you were in `/opt` and did git clone `https://github.com/tuxedocomputers/tuxedo-control-center.git` then the dev path would be `/opt/tuxedo-control-center/`

**Comment by mertanild** [comment]
Thank you mate. I'll try it now.

**Comment by vinzv** [comment]
Closing for now. If you need any assistance feel free to reopen!

**Comment by TamaMcGlinn** [comment]
so, at that point in the readme, there should be a dist/ directory that has been automatically created? There isn't, so I suspect there is some instruction missing after `npm install`.
