### ISSUE TITLE
Changing a language breaks the app

### ISSUE THREAD

**Issue by zolv** [tuxedocomputers/tuxedo-control-center#43]
After changing a language (just clicking on "Deutsch" icon) an app showed some garbage characters and this error:
![tuxedo-control-center-error](https://user-images.githubusercontent.com/10470118/91306640-1c659800-e7ad-11ea-95ea-621297c50da3.png)
I tried to remove it and install again and it's still the same.

**Comment by tuxedoxt** [comment]
If you reinstall or recently updated, make sure to also restart the app. There is a known issue with the app needing a manual restart. Should be fixed as of the new version, but could happen with this update.

**Comment by zolv** [comment]
Reinstalling didn't help but uninstalling, restarting my laptop and installing again fixed the issue.
I have also deleted a configuration directory in `~/.config/tuxedo-control-center`.
