### ISSUE TITLE
Battery-Life Saving by Locking AC Charge from Tuxedo Control Center

### ISSUE THREAD

**Issue by senaki** [tuxedocomputers/tuxedo-control-center#45]
I often remove my battery when I intend to do long duration tasks with my notebook (Tuxedo Book Dx1707) in order to preserve the battery life. But it could be annoying when I have to move, and forget my battery is not in place. 
A solution could be an option to allow **locking ac charge to a certain percentage of battery capacity** during the charge. For example, 80% of the battery capacity.

It could be handy for people who would prevent their battery from charging at 100% without thinking to unplug the power supply or removing it in view of not thinking about it later.

**Comment by vinzv** [comment]
There's no need to a) remove the battery and b) to implement such a feature into TCC as you already got that in your BIOS. :-)

It's called _Flexicharger_ and you can find out more about it here: https://www.tuxedocomputers.com/en/Infos/Help-Support/Frequently-asked-questions/How-can-I-extend-the-life-of-my-battery-.tuxedo

**Comment by KannebTo** [comment]
But for configuring the *Flexicharger* you must boot into the BIOS menu. To be able to setup this on a running system (via ACPI calls or so) might be a useful feature for TCC. It seems that *ThinkPads* are the only Laptops on which you can configure this on Linux. It would be nice to have such a feature on TUXEDO-Books too.
