### ISSUE TITLE
Root password required for profile change

### ISSUE THREAD

**Issue by fk0815** [tuxedocomputers/tuxedo-control-center#5]
My system is opensuse tumbleweed, I installed the rpm version 1.0.1 from the leap 15.1 tuxedo repository. That works, but for each profile change the root password needs to be entered. Can this be handled as normal user somehow?

**Comment by vinzv** [comment]
Hey there, thanks for asking!
As the steps need superuser permissions to interfere with your system there's no way around using root. But we already have a simplification of it to only ask for the password once on our roadmap. So expect it to come with some future version of TCC.

Meanwhile I'll close this issue. Feel free to reopen it or open a new one if you have further problems!
