### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by ghost** [tuxedocomputers/tuxedo-control-center#50]
Hello,

I have the following feature requests

- Did you plan to integrate a GUI for [tuxedo-keyboard](https://github.com/tuxedocomputers/tuxedo-keyboard) in the "Tools" section? There are already some GUIs for tuxedo-keyboard here on GitHub

-  Force Thunderbolt Power over GUI
   - I have see that you have a handfull devices with Thunderbolt 3. And a few Days ago i have readed that sometimes the Thunderbolt Controller or Thunderbolt devices will only be displayed when a Thunderbolt device is plugged in. It seems to be an energy saving feature of Thunderbolt. Would it be possible to add a toggle under "Tools" to force the power supply of the Thunderbolt controller?

It also would be very great to fill up the "Coming soon.." section in FEATURES.md or to have a PLANNED_FEATURES.md. So that we can see which features we can look forward to.

Thanks in advance

**Comment by tuxedoxt** [comment]
GUI keyboard backlight control is planned. Exact format is not yet decided, if it goes to the tools or be made profile controlled or both.

Good idea with the planned features list since there are always recurring inquiries about features.

Regarding thunderbolt.. got any sources, links or documentation on the topic? Possibly existing solutions by people?

**Comment by keyssant91** [comment]
- https://askubuntu.com/questions/1052380/no-thunderbolt-3-support-ubuntu-18-04
- https://unix.stackexchange.com/questions/468321/is-there-a-command-that-can-show-if-a-thunderbolt-port-is-present-on-the-hardwar


Solution is to force Thunderbolt power
https://wiki.archlinux.org/index.php/Thunderbolt#Forcing_power
https://www.kernel.org/doc/html/v5.8/admin-guide/thunderbolt.html?highlight=thunderbolt#forcing-power

**Comment by tuxedoxt** [comment]
According to the ubuntu link this is already solved by the `bolt` package. Had a quick look, it is installed by default in our ubuntu based installations. It is supposed to keep track of connection and only power it on while things are connected.
