### ISSUE TITLE
No tuxedo-cc-wmi found

### ISSUE THREAD

**Issue by nigelwarning** [tuxedocomputers/tuxedo-control-center#55]
Hey!

I never had this problem on Arch Linux.

But when I open Tuxedo CC there is no temperature indicator.
When I do sudo systemctl status tccd:

`● tccd.service - TUXEDO Control Center Service
     Loaded: loaded (/etc/systemd/system/tccd.service; enabled; vendor preset: >
     Active: active (running) since Mon 2020-11-09 19:43:06 CET; 20s ago
   Main PID: 458 (tccd)
      Tasks: 6 (limit: 38166)
     Memory: 43.2M
     CGroup: /system.slice/tccd.service
             └─458 /opt/tuxedo-control-center/resources/dist/tuxedo-control-cen>

Nov 09 19:43:06 arch systemd[1]: Started TUXEDO Control Center Service.
Nov 09 19:43:06 arch tccd[458]: Starting daemon v1.0.7 (node: v10.15.3 arch: x6>
Nov 09 19:43:06 arch tccd[458]: No tuxedo-cc-wmi found
Nov 09 19:43:06 arch tccd[458]: Daemon started
lines 1-13/13 (END)
`

When I restart the tccd service it does works. But I don't think is normal that every boot-yp I have to restart the laptop. Never had this problem before. As if a update did not something wrong.

I have a Clevo laptop.

**Comment by nigelwarning** [comment]
In Manjaro it does work.

Manjaro tccd[498]: Starting daemon v1.0.7 (node: v10.15.3 arch:>
nov 09 21:02:15 Manjaro tccd[498]: tuxedo-cc-wmi ver 0.1.7[ interface: clevo ]

**Comment by nigelwarning** [comment]
```
$ dkms status
tuxedo-cc-wmi, 0.1.7, 5.4.77-1-lts, x86_64: installed
tuxedo-cc-wmi, 0.1.7, 5.9.8-arch1-1, x86_64: installed
tuxedo-keyboard, 2.0.6, 5.4.77-1-lts, x86_64: installed
tuxedo-keyboard, 2.0.6, 5.9.8-arch1-1, x86_64: installed

```

Dkms shows everything installed. But on Arch still not works until you restart tccd.

**Comment by tuxedoxt** [comment]
Hello,

so somehow the tuxedo-cc-wmi module does load but after tccd? Unusual, but it should be able to recover anyways.

Did some quick testing and yeah if tccd starts after the module is loaded somehow the fan control part stays inactive although reporting "Control resumed". Does the tccd log say this in your case as well? (`journalctl -u tccd`)

So yeah this is a bug. Must be fan initialization that still has a dependency.

**Comment by nigelwarning** [comment]
Yes, same.
Did not had this in previous versions haha.

**Comment by nigelwarning** [comment]
I do have one question. Because It is not that I can easy send a private message. But even with this bug, will fan control still be controlled through the tuxedo control center or not? Or do I have to wait. I especially use the control center because without the fans are already making noice when the temps are 40 degrees.

**Comment by tuxedoxt** [comment]
> will fan control still be controlled through the tuxedo control center or not?

No, it seems if you don't reload tccd it does not initialize the fan control correctly afterwards. Until fixed `tuxedo-cc-wmi`needs to be loaded before `tccd` starts or `tccd` needs to be restarted for fan control to work.

**Comment by StevenSeifried** [comment]
Hello @nigelwarning 

i maintain the AUR Packages and use Arch Linux on my TUXEDO InfinityBook Pro 15 v4. I don't can confirm your problem.

Have you tried if adding `tuxedo-cc-wmi` to `MODULES` in `/etc/mkinitcpio.conf` solves the problem?

`MODULES=(i915 ext4 tuxedo_cc_wmi tuxedo_keyboard)`

**Comment by nigelwarning** [comment]
Addind `tuxedo-cc-wmi` to MODULES fixed this.

I never had to do this on earlier installs. It wasn't there before. Any reason why this wasn't enabled by default?

Thanks anyway

**Comment by lorenzosu** [comment]
Coming from #59 I seem to be hit by the same problem on Manjaro (tuxedo-cc-wmi 0.1.7-3 and tuxedo-control-center 1.0.7-1 from community) getting temperature 0° and fan 0%. Satrting manually like this doesn't work:
`systemctl start tccd`

I saw that the only work-around after reboot is to start manually:
`systemctl start tccd-sleep.service`

I noticed that the file `/etc/systemd/system/tccd-sleep.service` is as follows:

```bash
[Unit]
Description=TUXEDO Control Center Service (sleep/resume)
Before=sleep.target
StopWhenUnneeded=yes

[Service]
Type=oneshot
RemainAfterExit=yes
ExecStart=/bin/bash -c "systemctl stop tccd"
ExecStop=/bin/bash -c "systemctl start tccd"

[Install]
WantedBy=sleep.target
```
It seems that swapping the two `ExecStart` and `ExecStop` lines solved the problem in my case i.e. the new `/etc/systemd/system/tccd-sleep.service` file is:

```bash
[Unit]
Description=TUXEDO Control Center Service (sleep/resume)
Before=sleep.target
StopWhenUnneeded=yes

[Service]
Type=oneshot
RemainAfterExit=yes
ExecStart=/bin/bash -c "systemctl start tccd"
ExecStop=/bin/bash -c "systemctl stop tccd"

[Install]
WantedBy=sleep.target
```
Is this the correct approach?

**Comment by lorenzosu** [comment]
UPDATE: It seems the above is not correct because it doesn't 'survive' a power-off.
The name of that service prompted me to do another test and it seems if I put the machine to sleep (I'm on XFCE so with the 'Suspend' option) and wake it up again then TCC is working correctly.

**Comment by nigelwarning** [comment]
Already tried the modules way? That fixed the whole problem for me.

Op do 3 dec. 2020 om 14:05 schreef Lorenzo <notifications@github.com>:

**Comment by lorenzosu** [comment]
> Already tried the modules way? That fixed the whole problem for me. 

Infortunately changing /etc/mkinitcpio.conf as the above does not solve the problem here.

**Comment by nigelwarning** [comment]
My modules looks like this
**MODULES=(nvme tuxedo_cc_wmi)** See _ instead of - in the tuxedo cc wmi.

After that I had to run the following comment:
`sudo mkinitcpio -P`

And reboot to get it working :D

**Comment by lorenzosu** [comment]
@nigelwarning indeed I was missing the `sudo mkinitcpio -P` and this seems to have solved the problem.
However I now got a few cases where after boot-up the system randomly seems to be blocked to before log-in (I have automatic login with my user..). The system is somewhat responsive as it reboots if I do a CTRL + ALT + DEL three times, but (for instance) I don't get any virtual consoles (i.e. CTRL + ALT + F2 etc.). Any idea how I could go about debugging this?
