### ISSUE TITLE
"Image could not be created" error when building deb with modified TccFanTable.js values

### ISSUE THREAD

**Issue by luveti** [tuxedocomputers/tuxedo-control-center#61]
The following error dialog pops up when starting the built deb:

![image](https://user-images.githubusercontent.com/4952718/100307911-049cdc00-2f75-11eb-8017-765277afa6f0.png)

To reproduce:
- download the sources for release 1.0.7
- tweak the values of the Freezy profile
- build and install the deb
- try running the application

**Comment by tuxedoxt** [comment]
Hello, just verified that the build is not broken.

You could try a "fresh start". Also verify that it runs without your changes first.
- Delete the whole `node_modules` folder
- `npm install`
- `npm run pack-prod -- deb`

**Comment by tuxedoder** [comment]
I am unable to replicate this error when building the deb package myself. As version 2.1.7 is the latest release and this issue is related to 1.0.7, I will go ahead and close this issue. However, I can reopen this issue if the problem persists in the newest release.
