### ISSUE TITLE
Feature request: Support FlexiCharger

### ISSUE THREAD

**Issue by Apflkuacha** [tuxedocomputers/tuxedo-control-center#62]
It would be nice to change the FlexiCharger settings in Control Center, in addition to setting these values in BIOS. 
At least to enable/disable this feature would be great, so it could be quickly disabled without restarting the device if a full battery is necessary.

**Comment by gary094** [comment]
I would appreciate this as well. Would be great to set charging levels within the control center and also enable/disable flexicharge on the fly. I am often in the situation where I would like to have a 100% battery for the next day however it would be inconvenient to reboot.

**Comment by tuxedoxt** [comment]
Hello,

for the "flexicharger" feature, labeled as such in the bios settings there is (so far) no known interface for the OS.

For some other models that support "charging profiles" this feature is implemented as of v1.2.3

**Comment by gary094** [comment]
Thanks for implementing! Do you perhaps have a list somewhere which lists the models that received support for this feature in the control center? I am on v1.2.3 however there is no option for me on a Infinitybook S14 Gen6
