### ISSUE TITLE
Fan speed on boot

### ISSUE THREAD

**Issue by kladnik** [tuxedocomputers/tuxedo-control-center#63]
Hello! 

When ever I turn on the laptop the fans spin up to 100% for a second.
This is really annoying and it started to happen once I installed Tuxedo Control Panel.
Uninstalling TCC fixed it.

Laptop: Tuxedo Pulse 15
OS: Pop!_OS 20.10

Thanks

**Comment by tuxedoxt** [comment]
Hello,

try update the `tuxedo-keyboard`package to version `3.0.1`. There is an attempt at a workaround.

Please let me know how it works.

**Comment by kladnik** [comment]
Great, seems to work right now!
