### ISSUE TITLE
Support kernel 5.10

### ISSUE THREAD

**Issue by lorenzosu** [tuxedocomputers/tuxedo-control-center#68]
On 5.10.2-2 here (Manjaro) the frequency and fan don't seem to be supported (on 5.9 it works).

**Comment by HTOgit** [comment]
For me it works under the latest Manjaro.

**Comment by Olodin** [comment]
For me it is also working on Manjaro kernel 5.10. Be sure to install linux510-headers, for me it was not pulled in automatically. I had to reinstall tcc after that and works since then.

**Comment by lorenzosu** [comment]
Thanks @Olodin! Installing the headers did the trick. Shouldn't these be pulled in as a dependency though?

**Comment by tuxedoxt** [comment]
It's known to work on most of the 5 kernels. As Olodin says you of course need the headers and dkms working for the build of `tuxedo-keyboard`. Coincidentally tested on 5.11.0-rc3 the other day.

**Comment by vinzv** [comment]
> Thanks @Olodin! Installing the headers did the trick. Shouldn't these be pulled in as a dependency though?

That would be the packager's job of your distribution. I guess it should be fixed soon at Manjaro.
