### ISSUE TITLE
Build of version 1.0.1 fails on openSUSE Tumbleweed

### ISSUE THREAD

**Issue by happenpappen** [tuxedocomputers/tuxedo-control-center#7]
Hi,

when running "npm run build" on openSUSE Tumbleweed the build process starts but stops with:

> tuxedo-control-center@1.0.1 copy-native /home/cs/tuxedo-control-center-1.0.1
> (mkdir ./dist/tuxedo-control-center/service-app/native-lib || true) && cp ./build/Release/TuxedoECAPI.node ./dist/tuxedo-control-center/data/service && cp ./build/Release/TuxedoWMIAPI.node ./dist/tuxedo-control-center/data/service

mkdir: cannot create directory './dist/tuxedo-control-center/service-app/native-lib': File exists

**Comment by happenpappen** [comment]
The same happens, when working with a current clone of the git repository.

**Comment by vinzv** [comment]
Hey there, thanks for reporting the issue!

Is there any particular reason for building TCC manually? As an interim solution you could grab the Leap 15.1 version. I have it running on Tumbleweed myself and it works just fine.

```
zypper ar http://rpm.tuxedocomputers.com/opensuse/15.1/repo-tuxedo-computers.repo
zypper in tuxedo-control-center
```

**Comment by happenpappen** [comment]
Thank you for the link to the repository. I didn't use it, because i wasn't aware of it... it would be very helpful to have this link in the README.md of this repository. I tried the two zypper commands above, but they didn't work, because zypper complaint about an unknown repository type "repo-md" in the .repo file. I downloaded the .repo file and changed the line "type=repo-md" to "type=rpm-md", then it worked.

**Comment by vinzv** [comment]
You're right, that command was incorrect. I fixed it for future reference in my last reply.

Adding the information to the README is a good point. I'll take care of that.

**Comment by steadfasterX** [comment]
Fixed that particular error by removing:

`"(mkdir ./dist/tuxedo-control-center/service-app/native-lib || true) &&"`
from the `"copy-native"` line

for completeness a diff:

```
--- package.json.bak	2020-04-24 18:21:29.431363385 +0200
+++ package.json	2020-04-24 18:21:38.458062891 +0200
@@ -24,7 +24,7 @@
     "bundle-service": "pkg --target node10-linux-x64 --output ./dist/tuxedo-control-center/data/service/tccd ./dist/tuxedo-control-center/service-app/package.json",
     "build-native": "node-gyp configure && node-gyp rebuild",
     "copy-files": "run-s copy-package-json copy-dist-files copy-native",
-    "copy-native": "(mkdir ./dist/tuxedo-control-center/service-app/native-lib || true) && cp ./build/Release/TuxedoECAPI.node ./dist/tuxedo-control-center/data/service && cp ./build/Release/TuxedoWMIAPI.node ./dist/tuxedo-control-center/data/service",
+    "copy-native": "cp ./build/Release/TuxedoECAPI.node ./dist/tuxedo-control-center/data/service && cp ./build/Release/TuxedoWMIAPI.node ./dist/tuxedo-control-center/data/service",
     "copy-package-json": "cp ./src/package.json ./dist/tuxedo-control-center/package.json",
     "copy-dist-files": "cp -r ./src/dist-data ./dist/tuxedo-control-center/data",
     "copy-changelog": "cp CHANGELOG.md ./src/ng-app/assets/",
```

**Comment by tuxedoxt** [comment]
This is actually not an error but normal behaviour. Unless it aborts the build process. The `mkdir || true` command should only create a directory if it doesn't exist. Non optimally implemented (since it doesn't swallow the output and looks like an error), should probably be `mkdir -p` instead. I'll make a note to fix it.

In short: Can be ignored.

**Comment by steadfasterX** [comment]
> This is actually not an error but normal behaviour. Unless it aborts the build process. The `mkdir || true` command should only create a directory if it doesn't exist. Non optimally implemented (since it doesn't swallow the output and looks like an error), should probably be `mkdir -p` instead. I'll make a note to fix it.
> 
> In short: Can be ignored.

yes replacing `mkdir`with `mkdir -p` works fine as well

**Comment by tuxedoxt** [comment]
Put the `mkdir -p` version in repo in case it's needed. Should provide less confusion ^^
