### ISSUE TITLE
[feature request] add support for AMD ryzen boost mode to Control Center for pulse 15

### ISSUE THREAD

**Issue by yeus** [tuxedocomputers/tuxedo-control-center#70]
Right now it is only possible to control the number of cores and clock speed up to 2.9GHz base speed from control center. It would be nice to have a option in order to enable boost mode as well.

**Comment by tuxedoxt** [comment]
Hello, this is not so intuitive but for AMD devices setting the maximum frequency to the maximum value (lower than boost frequencies) does not disable boost frequencies. This is how the controlling interface is presented from Linux. We might attempt to abstract this to something more intuitive in the future.

**Comment by yeus** [comment]
Ok, thx for the explanation!
