### ISSUE TITLE
Pulse 15 does not support balanced fan control mode

### ISSUE THREAD

**Issue by febluthn** [tuxedocomputers/tuxedo-control-center#71]
The Default Profile on the Pulse 15 set the balanced mode for fan control. If I set the mode manually in a custom profile I got a hint that  this feature is not supported by that device. This message does only not appear on silent and quiet mode.

If there no balanced mode for pulse 15 or is the hint incorrect?

**Comment by tuxedoxt** [comment]
Hello,

if it only appears quickly while the settings are saved this is a known glitch. Otherwise, this should not happen. All the fan profiles are available for this device.

Could you provide a screenshot?

**Comment by febluthn** [comment]
of course
![Bildschirmfoto von 2021-01-18 10-56-54](https://user-images.githubusercontent.com/59641869/104900496-67f72900-597c-11eb-8363-c27af9bdbbff.png)

**Comment by HTOgit** [comment]
This happens when you change the profile and your cursor is then over the menu for the "webcam". Deactivating the webcam is not possible with the Pulse15.

**Comment by tuxedoxt** [comment]
> This happens when you change the profile and your cursor is then over the menu for the "webcam". Deactivating the webcam is not possible with the Pulse15.

Correct, the webcam looks correctly blurred-out and would explain the tooltip. Could it be that the mouse cursor ends up mousing over the webcam area when selecting the fan profile?

**Comment by febluthn** [comment]
Yep, this is very likely, but also confusing. I tried out all fan modes and they seems to work.
