### ISSUE TITLE
Building on 20.10 - Polaris 15 - SEGV core-dump

### ISSUE THREAD

**Issue by kmscks** [tuxedocomputers/tuxedo-control-center#73]
Hello,
I'm trying to build from source. I'm running Kubuntu 20.10, 5.8.0-40-generic, on a Polaris 15 with ryzen 4800h. 
I have  tuxedo-keyboard 3.0.0, also built from source. 

I followed every step, copied tccd.service + tccd-sleep.service in /etc/systemd/system/, and pointed towards my working copy. 

The service starts but fails : 
- failed (Result: core-dump)
- Process: 11915 ExecStart=*********/src/tuxedo-control-center/dist/tuxedo-control-center/data/service/tccd --start (code=dumped, signal=SEGV) 
- Main PID: 11915 (code=dumped, signal=SEGV)
- janv. 23 13:29:53 ******* systemd[1]: Started TUXEDO Control Center Service.
- janv. 23 13:29:54 ******* systemd[1]: tccd.service: Main process exited, code=dumped, status=11/SEGV
- janv. 23 13:29:54 ******* systemd[1]: tccd.service: Failed with result 'core-dump'.

Is there something I could try or is this a know issue ? 
I would be happy to try things if that could help ;)

**Comment by tuxedoxt** [comment]
Hello,

this is no known problem. It seems to segfault somewhere on startup.

- You can try the node version that is currently in the readme, I believe version 12.
- Also you do not mention copying the dbus conf file. This is necessary to allow the dbus service to start up. I do not know why it would segfault without however.

**Comment by kmscks** [comment]
@tuxedoxt : 
- I'm running v12, as per recommended.
- I did copy the dbus conf, just forgot to mention it.

**Comment by Matombo** [comment]
Hi,
I just ran into the same problem as you using npm 6.14.4 from the Ubuntu 20.04 repos.
Running https://deb.nodesource.com/setup_12.x and installing npm again pushed it to 6.14.10, which compiles a non segfaulting tccd.
Can please check if this also works on your setup?

**Comment by kmscks** [comment]
> Hi,
> I just ran into the same problem as you using npm 6.14.4 from the Ubuntu 20.04 repos.
> Running https://deb.nodesource.com/setup_12.x and installing npm again pushed it to 6.14.10, which compiles a non segfaulting tccd.
> Can please check if this also works on your setup?

Thanks, that did it ! 
Maybe I should mention that I was not running the Ubuntu 20.04 repo version (6.14.4), but I was running 6.14.8 (from 20.10 repo). 
I pushed node to 12.20.1 and npm to 7.5.2.
So I gather tcc requires npm >= 6.14.10

**Comment by tuxedoder** [comment]
It looks like this issue is solved, so I am closing it.
