### ISSUE TITLE
High Temperature, Low CPU on TUXEDO InfinityBook S 14 Gen6 @ ArchLinux

### ISSUE THREAD

**Issue by t-oster** [tuxedocomputers/tuxedo-control-center#74]
Hi,

I recently bought a TUXEDO InfinityBook S 14 Gen6 and I am running Arch Linux with TCC 1.0.8.
I changed my profile to CPU 3.5-4.7 Ghz, and freezy CPU fans.
However, the CPU Temperature is always between 60-70°C, while the fan does not get faster than 50%. The Frequency goes down in the middle of cpu intensive tasks to 400 Mhz effectively blocking me from doing anything productive.

I know ArchLinux is not supported, but is there any chance to debug this? What are the usual temperature values for the 
TUXEDO InfinityBook S 14 Gen6 and why can the frequency drop below my low limit of 3.5 Ghz?

Once it completely froze so I had to reboot.

**Comment by boppy** [comment]
I have a similar problem with my v5 S14 on arch.

The set CPU limits seem not to be enforced:

![speed-please-500](https://user-images.githubusercontent.com/749141/106493747-da5a2400-64b9-11eb-88b4-c92418341a4d.png)


In fact the load is kind of high on my device (chrome ftw), but the CPU gets throttled to 400 MHz from time to time. If I apply more load, the Core Speed goes up from, but my "1.8 GHz" limit is not enforced.

@t-oster Don't mind using arch, btw. :-D The (awesome) support-crew also has (at least) one Tux using an arch based system.

**Comment by t-oster** [comment]
I tried on ubuntu lts with the tuxedo.sh applied. It may have been a bit better, but still the limits were not enforced. I guess 15W is just not enough power for intensive workloads. I would have expected the fans to go to 100% before the frequency is throttled though. However I think the S14 is just not the right notebook for my needs.

@boppy feel free to reopen this issue if it affects you
