### ISSUE TITLE
TCC will not autostart

### ISSUE THREAD

**Issue by MarcusFloeser** [tuxedocomputers/tuxedo-control-center#79]
Starting initially with "npm run start" .. but I got error on toggeling tray autostart:
prime-select: command not found
prime-supported: command not found

This leads to not enabled autostart of tcc.

How to find the issue?

System is Solus 4.2

**Comment by tuxedoxt** [comment]
Hello, the prime messages should be unrelated to the enabling of the autostart.

Autostart file should be installed to `~/.config/autostart`. However if you only run it in "dev mode" manually with `npm run start` autostart will not work since the target file is not installed.

**Comment by MarcusFloeser** [comment]
ok, working now as expected
