### ISSUE TITLE
Profiles for fan tables

### ISSUE THREAD

**Issue by MDosky** [tuxedocomputers/tuxedo-control-center#8]
We should be able to create our own fan profiles.
Since TccFanTable.ts exists this should be a no-brainer apart from the UI.

**Comment by konstantinosKokos** [comment]
Would also appreciate this feature without having to build from scratch

**Comment by yuyuen72** [comment]
Exactly, I think I really need this feature.

**Comment by brunoais** [comment]
This is already partially implemented with the two sliders for fans. It can still improve, though.

**Comment by tuxedoder** [comment]
Users now have the ability to create a custom fan curve for personalized fan behavior within tcc.
