### ISSUE TITLE
Package process

### ISSUE THREAD

**Issue by ThatComputerKid** [tuxedocomputers/tuxedo-control-center#82]
Hey guys, I want to make an RPM for Fedora of TCC. Could anyone tell me how the Suse RPM is built? I understand that it starts with npm build, but how do you slim it down into a package?

**Comment by KallePM** [comment]
I don't know if this is still relevant to you, but I did a [Copr build](https://copr.fedorainfracloud.org/coprs/kallepm/tuxedo-control-center/) that you could test if you want.
I can confirm cpu settings and screen brightness works.
Other features are not supported on my machine (Via 15 Pro), even with the official build.
Therefore those other settings might as well just work fine.

**Comment by schewara** [comment]
@KallePM you are a lifesaver :1st_place_medal:

**Comment by tuxedoxt** [comment]
Ah this went unanswered. The relevant build configuration file is https://github.com/tuxedocomputers/tuxedo-control-center/blob/master/build-src/electron-builder.ts where there is an entry for the suse rpm build.

**Comment by ThatComputerKid** [comment]
> I don't know if this is still relevant to you, but I did a [Copr build](https://copr.fedorainfracloud.org/coprs/kallepm/tuxedo-control-center/) that you could test if you want.
> I can confirm cpu settings and screen brightness works.
> Other features are not supported on my machine (Via 15 Pro), even with the official build.
> Therefore those other settings might as well just work fine.

Thanks so much @KallePM ! This is super useful. Ever thought of getting this packaged into the official repos? That would be amazing.

**Comment by vinzv** [comment]
COPR package looks good, thanks!
Closing for now.
