### ISSUE TITLE
Howto start TCC on Debian 10

### ISSUE THREAD

**Issue by MarcusFloeser** [tuxedocomputers/tuxedo-control-center#84]
Hello,

I have installed successfully TCC on Netrunner XUL based on Debia 10.7.
However I have to manually start TCC with "npm run start".
How can I autostart it in Debian? I tried to add it to "Autostart" but it will not start...

Any idea?

**Comment by vinzv** [comment]
For Debian you could try installing the pre-built packages from https://deb.tuxedocomputers.com/ubuntu/pool/main/t/tuxedo-control-center/
I just tried them and autostart works just fine ootb.
