### ISSUE TITLE
Where is <dev path>/dist/tuxedo-control-center/data/service/tccd?

### ISSUE THREAD

**Issue by muffinmaster1024** [tuxedocomputers/tuxedo-control-center#89]
As written above...
Building from source on Ubuntu 20.10: 
I can't find any matching path. What is meant by <dev path>?

**Comment by TamaMcGlinn** [comment]
I have the same question, but I have no idea what you mean when you marked this as completed. The readme is still clear as mud, `npm build` says "Unknown command: "build"", and I don't see what attempting to make a new empty directory but with three dots appended erroneously is going to do to fix this.

**Comment by tuxedoxt** [comment]
Hello,

`dist` should be created automatically by the build script(s).

Here's the readme part for how to execute npm scripts and which are available: https://github.com/tuxedocomputers/tuxedo-control-center#npm-scripts
