### ISSUE TITLE
seccomp-bpf failure

### ISSUE THREAD

**Issue by steadfasterX** [tuxedocomputers/tuxedo-control-center#9]
```
> tuxedo-control-center@1.0.1 start /home/xxxxx/programs/tuxedo-control-center
> electron ./dist/tuxedo-control-center

../../sandbox/linux/seccomp-bpf-helpers/sigsys_handlers.cc:**CRASHING**:seccomp-bpf failure in syscall 0230
../../sandbox/linux/seccomp-bpf-helpers/sigsys_handlers.cc:**CRASHING**:seccomp-bpf failure in syscall 0230
../../sandbox/linux/seccomp-bpf-helpers/sigsys_handlers.cc:**CRASHING**:seccomp-bpf failure in syscall 0230
```

looks like a known issue with the chromium engine:

- https://bugzilla.redhat.com/show_bug.cgi?id=1773289
- https://bugs.chromium.org/p/chromium/issues/detail?id=1025739
- https://gitlab.alpinelinux.org/alpine/aports/issues/10257
- https://forum.endeavouros.com/t/chromium-based-browser-crashes-solution/3595

while I am new to that NPM/electron stuff so no idea where to look/start fixing that..

jfi: I am on Manjaro Linux ;)

**Comment by tuxedoxt** [comment]
Hmm I have not seen this one yet. Tried another glibc version?

**Comment by steadfasterX** [comment]
> Hmm I have not seen this one yet. Tried another glibc version?

how can I do that?

**Comment by steadfasterX** [comment]
I have retried without npm audit fix and not get this:


![image](https://user-images.githubusercontent.com/8750713/80578797-54301f00-8a09-11ea-96a2-ebbc236b4300.png)

**Comment by tuxedoxt** [comment]
Wow, so another npm audit fix problem.

Ok, this is normal without configuring the service.

If you have access to a packaged version and don't want to touch the service code you can use this in general.

I have not added specific instructions or automatic dev installation for the service yet. Basically you need three files.

Copy `tccd.service` and `tccd-sleep.service` (from src/dist-data) to `/etc/systemd/system/`. Edit the `tccd.service` (exec start/stop) to point to `<dev path>/dist/tuxedo-control-center/data/service/tccd`. And copy `com.tuxedocomputers.tccd.conf` to `/usr/share/dbus-1/system.d/`

Then start service `systemctl start tccd`. (And enable if you want autostarted `systemctl enable tccd tccd-sleep`).

**Comment by steadfasterX** [comment]
> Wow, so another npm audit fix problem.
> 
> Ok, this is normal without configuring the service. [....]

well yea if you see after the build a warning about "**450 vulnerabilities found**" then users might get scared (like me) and following the advice to fix... :) which actually break things ofc.. :(

just for info the **seccomp** failures are still there! just the tccd message is new.. will try your guide regarding the service, thx!

**Comment by tuxedoxt** [comment]
> > Wow, so another npm audit fix problem.
> > Ok, this is normal without configuring the service. [....]
> 
> well yea if you see after the build a warning about "**450 vulnerabilities found**" then users might get scared (like me) and following the advice to fix... :) which actually break things ofc.. :(
> 
> just for info the **seccomp** failures are still there! just the tccd message is new.. will try your guide regarding the service, thx!

Hmm ok. Yeah I see the problem ^^

**Comment by steadfasterX** [comment]
@tuxedoxt 

yea now it brings up the GUI :+1:  :) thanks again!

![image](https://user-images.githubusercontent.com/8750713/80582089-6d879a00-8a0e-11ea-8430-a18861286055.png)

now I "just" need to find out how to fix the not supporting stuff there ;)

**Comment by tuxedoxt** [comment]
> @tuxedoxt
> 
> yea now it brings up the GUI +1 :) thanks again!
> 
> ![image](https://user-images.githubusercontent.com/8750713/80582089-6d879a00-8a0e-11ea-8430-a18861286055.png)
> 
> now I "just" need to find out how to fix the not supporting stuff there ;)

Great, yeah, hint, tuxedo-cc-wmi ;)

**Comment by steadfasterX** [comment]
it seems.. that this error can be safely ignored (initial error message for this issue) so I close it. thanks for the quick and helpful support!
