### ISSUE TITLE
Can't change profile on Arch

### ISSUE THREAD

**Issue by marcempunkt** [tuxedocomputers/tuxedo-control-center#92]
Hi,
I've installed Arch on my TUXEDO InfinityBook S 15 Gen6 with the 11th Gen Intel i7-1165G7. 
I've installed tuxedo-control-center with the aur, but I couldn't change my profile.

After starting the tuxedo-control-center with `sudo tuxedo-control-center --no-sandbox` I got this output in the terminal:

```
/bin/sh: line 1: prime-select: command not found
/bin/sh: line 1: prime-supported: command not found

(tuxedo-control-center:1307): libappindicator-WARNING **: 15:54:35.687: Unable to get the session bus: Unknown or unsupported transport ?disabled? for address ?disabled:?

(tuxedo-control-center:1307): LIBDBUSMENU-GLIB-WARNING **: 15:54:35.697: Unable to get session bus: Unknown or unsupported transport ?disabled? for address ?disabled:?
```

But git cloning tuxedo-control-center, running `npm run build` & `npm run start` got me this error message after changing profile & typing my password in:

```
==== AUTHENTICATING FOR org.freedesktop.policykit.exec ====
Authentication is needed to run `/home/marc/Documents/Projects/tuxedo-control-center/dist/tuxedo-control-center/data/service/tccd' as the super user
Authenticating as: marc
Password:
==== AUTHENTICATION FAILED ====
```

I'm pretty sure I'm typing the correct password ^^

**Comment by tuxedoxt** [comment]
Hmm `tuxedo-control-center` is not meant to be run with privileges. Maybe we need to prevent this. The daemon part `tccd` is however.

As far as I hear there are working AUR packages and what I would recommend. @StevenSeifried, known issues ?

**Comment by marcempunkt** [comment]
Simply starting `tuxedo-control-center` without `sudo` doesn't not give me any output to the terminal.
When I normally start `tuxedo-control-center` installed as a aur package, it simply does nothing when changing profiles.
Strangely enough before Arch I had Parabola installed and `tuxedo-control-center` worked out of the box...

**Comment by tuxedoxt** [comment]
When changing profile, do you get the policy kit password prompt (normally gui)?

**Comment by marcempunkt** [comment]
No not at all. The whole app blurs for a second and goes back to normal without changing the profile.

**Comment by tuxedoxt** [comment]
What happens if you type for example `pkexec pwd` in a terminal?

**Comment by marcempunkt** [comment]
`pkexec pwd`

```
==== AUTHENTICATING FOR org.freedesktop.policykit.exec ====
Authentication is needed to run `/usr/bin/pwd' as the super user
Authenticating as: marc
Password:
polkit-agent-helper-1: error response to PolicyKit daemon: GDBus.Error:org.freedesktop.PolicyKit1.Error.Failed: No session for cookie
==== AUTHENTICATION FAILED ====
Error executing command as another user: Not authorized

This incident has been reported.
```

**Comment by tuxedoxt** [comment]
Ok at least two issues there
- Policy kit does not offer GUI password input on your system as it "normally" does
- Policy kit authentication fails for your user on your system. Privileges maybe configured for other user?

**Comment by morla10111** [comment]
> Hi,
> I've installed Arch on my TUXEDO InfinityBook S 15 Gen6 with the 11th Gen Intel i7-1165G7.
> I've installed tuxedo-control-center with the aur, but I couldn't change my profile.
> 
> After starting the tuxedo-control-center with `sudo tuxedo-control-center --no-sandbox` I got this output in the terminal:
> 
> ```
> /bin/sh: line 1: prime-select: command not found
> /bin/sh: line 1: prime-supported: command not found
> 
> (tuxedo-control-center:1307): libappindicator-WARNING **: 15:54:35.687: Unable to get the session bus: Unknown or unsupported transport ?disabled? for address ?disabled:?
> 
> (tuxedo-control-center:1307): LIBDBUSMENU-GLIB-WARNING **: 15:54:35.697: Unable to get session bus: Unknown or unsupported transport ?disabled? for address ?disabled:?
> ```
> 
> But git cloning tuxedo-control-center, running `npm run build` & `npm run start` got me this error message after changing profile & typing my password in:
> 
> ```
> ==== AUTHENTICATING FOR org.freedesktop.policykit.exec ====
> Authentication is needed to run `/home/marc/Documents/Projects/tuxedo-control-center/dist/tuxedo-control-center/data/service/tccd' as the super user
> Authenticating as: marc
> Password:
> ==== AUTHENTICATION FAILED ====
> ```
> 
> I'm pretty sure I'm typing the correct password ^^

Hello,
running on Void Linux here. Having the same problem. When i run  tuxedo-control-center, my cores are set to 400Mhz.

Best regards,
moe

**Comment by marcempunkt** [comment]
> Ok at least two issues there
> 
>     * Policy kit does not offer GUI password input on your system as it "normally" does
> 
>     * Policy kit authentication fails for your user on your system. Privileges maybe configured for other user?

So I've installed `polkit`, `lxsession` & run `/usr/bin/lxpolkit` for testing and it worked!
Basically everything in detail is described in https://wiki.archlinux.org/index.php/Polkit

@morla10111 As for void linux you have to look for yourself which package you want or can install.
